CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS vector;

ALTER DATABASE etl SET timezone TO 'Asia/Seoul';

-- ── companies ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
    id                 BIGSERIAL PRIMARY KEY,
    name               TEXT NOT NULL,
    country            TEXT NOT NULL,
    is_listed          BOOLEAN NOT NULL,
    description        TEXT,
    description_source TEXT,
    corp_code          TEXT,
    wikidata_qid       TEXT,
    ceo_name           TEXT,
    industry_code      TEXT,
    established_on     DATE,
    fiscal_month       TEXT,
    homepage           TEXT,
    address            TEXT,
    ticker             VARCHAR(20),
    delisted_at        DATE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_active_ticker_uk
  ON companies (ticker) WHERE delisted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_corp_code_uk
  ON companies (corp_code) WHERE corp_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_wikidata_uk
  ON companies (wikidata_qid) WHERE wikidata_qid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies (name);
CREATE INDEX IF NOT EXISTS companies_country_idx ON companies (country);

-- ── company_aliases ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS company_aliases (
    id         BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    alias      TEXT   NOT NULL,
    lang       TEXT,
    source     TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (alias, company_id)
);

CREATE INDEX IF NOT EXISTS company_aliases_alias_idx   ON company_aliases (alias);
CREATE INDEX IF NOT EXISTS company_aliases_company_idx ON company_aliases (company_id);

-- ── company_financials ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS company_financials (
    id                BIGSERIAL PRIMARY KEY,
    company_id        BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    source            TEXT NOT NULL,
    fiscal_yymm       TEXT NOT NULL,
    period_type       TEXT NOT NULL,   -- 'Q' | 'A'
    fs_div            TEXT,            -- 'CFS' | 'OFS'
    disclosed_at      DATE,
    rcept_no          TEXT,
    revenue           BIGINT,
    operating_income  BIGINT,
    net_income        BIGINT,
    roe               NUMERIC,
    total_assets      BIGINT,
    total_liabilities BIGINT,
    total_equity      BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, fiscal_yymm, period_type, fs_div, source)
);

-- ── stocks ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stocks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT REFERENCES companies (id),
    market               TEXT NOT NULL,
    ticker               TEXT NOT NULL,
    name                 TEXT NOT NULL,
    listed_date          DATE,
    delisted_at          DATE,
    is_active            BOOLEAN NOT NULL DEFAULT true,
    trading_suspended    BOOLEAN NOT NULL DEFAULT false,
    under_administration BOOLEAN NOT NULL DEFAULT false,
    delisting_trade      BOOLEAN NOT NULL DEFAULT false,
    listed_shares        BIGINT,
    par_value            NUMERIC,
    capital              BIGINT,
    source               TEXT NOT NULL DEFAULT 'KIS_MASTER',
    raw_attributes       JSONB,
    synced_at            TIMESTAMPTZ,
    standard_code        TEXT NOT NULL, 
    preferred_stock      BOOLEAN NOT NULL DEFAULT false,   -- 이하 3종: 법인 이관·서비스 대상 필터
    etp                  BOOLEAN NOT NULL DEFAULT false,
    spac                 BOOLEAN NOT NULL DEFAULT false,
    inactive_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS stocks_standard_code_uk ON stocks (standard_code);
CREATE UNIQUE INDEX IF NOT EXISTS stocks_active_ticker_uk ON stocks (ticker) WHERE is_active;
CREATE INDEX IF NOT EXISTS stocks_company_id_idx ON stocks (company_id);

-- ── 시세 · 수급 · 배당 · 밸류에이션 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_candles (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date  DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    source      TEXT    NOT NULL,   -- 'FDR' | 'KIS'
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS daily_candles_date_idx ON daily_candles (trade_date);

-- 주봉·월봉 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_period_candles (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    period      TEXT    NOT NULL,   -- 'W' | 'M'
    base_date   DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, period, base_date)
);

CREATE TABLE IF NOT EXISTS investor_flows (
    stock_id        BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date      DATE   NOT NULL,
    personal_net    BIGINT,
    institution_net BIGINT,
    foreign_net     BIGINT,
    foreign_ratio   NUMERIC,
    trust_net       BIGINT,
    pension_net     BIGINT,
    insurance_net   BIGINT,
    bank_net        BIGINT,
    etc_corp_net    BIGINT,
    PRIMARY KEY (stock_id, trade_date)
);

CREATE TABLE IF NOT EXISTS dividends (
    listing_id  BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    record_date DATE   NOT NULL,
    divi_kind   TEXT   NOT NULL,
    dps         NUMERIC,
    pay_date    DATE,
    PRIMARY KEY (listing_id, record_date, divi_kind)
);

CREATE TABLE IF NOT EXISTS valuation_daily (
    listing_id     BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date     DATE   NOT NULL,
    market_cap     BIGINT,
    per            NUMERIC,
    pbr            NUMERIC,
    eps            NUMERIC,
    bps            NUMERIC,
    dividend_yield NUMERIC,
    r_1w           NUMERIC,
    r_1m           NUMERIC,
    r_3m           NUMERIC,
    PRIMARY KEY (listing_id, trade_date)
);

-- ── news ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS news (
    id                 BIGSERIAL PRIMARY KEY,
    title              TEXT,
    text               TEXT,
    summary            TEXT,
    link               TEXT UNIQUE,
    originallink       TEXT,
    published_at       TIMESTAMPTZ,
    is_material        BOOLEAN,
    source_type        VARCHAR(20),
    collected_at       TIMESTAMPTZ DEFAULT now(),
    relation_extracted BOOLEAN
);

-- ── news_relations ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS news_relations (
    id           BIGSERIAL PRIMARY KEY,
    news_id      BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    subject_name TEXT NOT NULL,
    subject_type VARCHAR(20) NOT NULL,
    subject_code VARCHAR(20),
    relation     VARCHAR(30) NOT NULL,
    object_name  TEXT NOT NULL,
    object_type  VARCHAR(20) NOT NULL,
    object_code  VARCHAR(20),
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (news_id, subject_name, relation, object_name)
);

CREATE INDEX IF NOT EXISTS idx_news_relations_subject_code
  ON news_relations (subject_code) WHERE subject_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_news_relations_object_code
  ON news_relations (object_code) WHERE object_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_news_relations_subject_name ON news_relations (subject_name);
CREATE INDEX IF NOT EXISTS idx_news_relations_object_name  ON news_relations (object_name);
CREATE INDEX IF NOT EXISTS idx_news_relations_triple
  ON news_relations (subject_name, relation, object_name);
CREATE INDEX IF NOT EXISTS idx_news_relations_news ON news_relations (news_id);

CREATE OR REPLACE VIEW news_companies AS
SELECT DISTINCT news_id, subject_name AS company_name, subject_code AS ticker
FROM news_relations WHERE subject_type = 'COMPANY'
UNION
SELECT DISTINCT news_id, object_name, object_code
FROM news_relations WHERE object_type = 'COMPANY';

CREATE OR REPLACE VIEW entities_relations AS
SELECT subject_name, subject_type, relation, object_name, object_type,
       count(*)          AS news_count,
       min(extracted_at) AS first_seen,
       max(extracted_at) AS last_seen
FROM news_relations
GROUP BY 1, 2, 3, 4, 5;

-- ── themes ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS themes (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS theme_stocks (
    id       BIGSERIAL PRIMARY KEY,
    theme_id BIGINT NOT NULL REFERENCES themes (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    reason   TEXT,
    UNIQUE (theme_id, stock_id)
);

CREATE INDEX IF NOT EXISTS theme_stocks_theme_idx ON theme_stocks (theme_id);
CREATE INDEX IF NOT EXISTS theme_stocks_stock_idx ON theme_stocks (stock_id);

CREATE TABLE IF NOT EXISTS news_themes (
    id         BIGSERIAL PRIMARY KEY,
    news_id    BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    theme_id   BIGINT NOT NULL REFERENCES themes (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (news_id, theme_id)
);

CREATE INDEX IF NOT EXISTS idx_news_themes_theme ON news_themes (theme_id);
CREATE INDEX IF NOT EXISTS idx_news_themes_news  ON news_themes (news_id);

-- ── search_keywords ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS search_keywords (
    id               BIGSERIAL PRIMARY KEY,
    keyword          TEXT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_searched_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_search_keywords_last_searched
  ON search_keywords (last_searched_at);

INSERT INTO search_keywords (keyword)
VALUES
    ('인수'), ('합병'), ('매각'), ('분할'), ('분사'), ('제휴'),
    ('수주'), ('낙찰'), ('입찰'), ('공급계약'), ('납품'),
    ('수출'), ('수입'), ('증산'), ('감산'), ('채굴'),
    ('제재'), ('규제'), ('관세'), ('수출 금지'), ('수입 금지'),
    ('협정 체결'), ('협정 파기'), ('국교 단절'), ('침공'), ('봉쇄'), ('휴전'),
    ('소송'), ('국유화'),
    ('특징주')
ON CONFLICT (keyword) DO NOTHING;
