-- 0000: 신규 DB 기준 베이스라인 DDL (전체 스키마)
--
-- 구 0000~0003 마이그레이션을 최종 상태로 통합한 단일 베이스라인이다. 운영 DB가 없다는
-- 전제라 ALTER/DROP 없이 초기 스키마만 적는다. 반복 적용 안전(idempotent)하다.
--
-- 적재 흐름의 큰 그림:
--   companies/stocks  ← KIS·DART 마스터 동기화
--   news              ← 네이버 뉴스 수집 (search_keywords 가 검색 쿼리 원천)
--   disclosures       ← DART 공급계약 공시 수집
--   relation_sources  ← 뉴스(LLM 삼중항 추출)·공시가 함께 쓰는 근거 원장.
--                       Neo4j 간선은 이 원장의 집계(entities_relations 뷰)를 캐시한
--                       파생이라, 그래프는 언제든 원장에서 전량 재구성할 수 있다.

CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET timezone TO ''Asia/Seoul''', current_database());
END $$;

-- ── companies ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
    id                   BIGSERIAL PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               VARCHAR(20),
    corp_code            TEXT,
    is_listed            BOOLEAN NOT NULL,
    description          TEXT,
    description_source   TEXT,
    -- 설명을 만든 원천 공시. 새 보고서가 없으면 설명을 다시 만들지 않는다.
    description_rcept_no TEXT,
    wikidata_qid         TEXT,
    ceo_name             TEXT,
    country              TEXT NOT NULL,
    industry_code        TEXT,
    established_on       DATE,
    fiscal_month         TEXT,
    homepage             TEXT,
    address              TEXT,
    delisted_at          DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_active_ticker_uk
  ON companies (ticker) WHERE delisted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_corp_code_uk
  ON companies (corp_code) WHERE corp_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_wikidata_uk
  ON companies (wikidata_qid) WHERE wikidata_qid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies (name);
CREATE INDEX IF NOT EXISTS companies_country_idx ON companies (country);

-- ── company_aliases ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS company_aliases (
    id         BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    alias      TEXT   NOT NULL,
    lang       TEXT,
    source     TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (alias, company_id)
);

CREATE INDEX IF NOT EXISTS company_aliases_alias_idx   ON company_aliases (alias);
CREATE INDEX IF NOT EXISTS company_aliases_company_idx ON company_aliases (company_id);

-- ── company_financials ──────────────────────────────────────────────────────
--
-- period_type 에 'QC' 가 있다. KIS 분기 재무는 **연초부터의 누적**이라 그대로 쓰면
-- 1분기 EPS 를 1년치로 나누게 되고 PER 이 최대 9배 부푼다(2026-08-18 네이버·토스 11종목
-- 대조 확인). 누적은 QC 로 담고 분기 개별값 Q 는 차분해서 만든다.
--
--     A    연간
--     QC   분기 누적   ← KIS 원본
--     Q    분기 개별   ← QC 에서 차분
--
-- eps·bps 는 PER·PBR 의 분모라 없으면 밸류에이션이 성립하지 않는다.
-- KIS 재무비율 API 가 직접 주는 값이라 계산하지 않는다.
CREATE TABLE IF NOT EXISTS company_financials (
    id                BIGSERIAL PRIMARY KEY,
    company_id        BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    source            TEXT NOT NULL,
    fiscal_yymm       TEXT NOT NULL,
    period_type       TEXT NOT NULL,   -- 'A' | 'QC' | 'Q'
    fs_div            TEXT,            -- 'CFS' | 'OFS'
    disclosed_at      DATE,
    rcept_no          TEXT,
    revenue           BIGINT,
    operating_income  BIGINT,
    net_income        BIGINT,
    roe               NUMERIC,
    eps               NUMERIC,
    bps               NUMERIC,
    total_assets      BIGINT,
    total_liabilities BIGINT,
    total_equity      BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 유니크에 rcept_no 를 넣는다. DART 정정공시는 같은 회계기간에 접수번호만 다른 행으로
-- 오는데, 접수번호가 키에 없으면 정정본이 원본을 덮어써 이력이 사라진다.
-- KIS 행은 접수번호가 없으므로 COALESCE 로 빈 문자열을 대신 넣는다.
-- 표현식을 쓰므로 테이블 제약(UNIQUE)이 아니라 인덱스로 만든다.
CREATE UNIQUE INDEX IF NOT EXISTS company_financials_uk
    ON company_financials (company_id, source, fs_div, fiscal_yymm, period_type, COALESCE(rcept_no, ''));

CREATE INDEX IF NOT EXISTS company_financials_lookup_idx
    ON company_financials (company_id, period_type, fiscal_yymm DESC);

-- ── stocks ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stocks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               TEXT NOT NULL,
    market               TEXT NOT NULL,
    company_id           BIGINT REFERENCES companies (id),
    standard_code        TEXT NOT NULL,
    listed_date          DATE,
    delisted_at          DATE,
    is_active            BOOLEAN NOT NULL DEFAULT true,
    trading_suspended    BOOLEAN NOT NULL DEFAULT false,
    under_administration BOOLEAN NOT NULL DEFAULT false,
    delisting_trade      BOOLEAN NOT NULL DEFAULT false,
    listed_shares        BIGINT,
    par_value            NUMERIC,
    capital              BIGINT,
    source               TEXT NOT NULL DEFAULT 'KIS_MASTER',
    -- KIS master 증권그룹구분코드. 주권 'ST'만 법인(companies)으로 이관
    security_group       TEXT,
    preferred_stock      BOOLEAN NOT NULL DEFAULT false,   -- 이하 3종: 법인 이관·서비스 대상 필터
    etp                  BOOLEAN NOT NULL DEFAULT false,
    spac                 BOOLEAN NOT NULL DEFAULT false,
    inactive_at          TIMESTAMPTZ,
    raw_attributes       JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    synced_at            TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS stocks_standard_code_uk ON stocks (standard_code);
CREATE UNIQUE INDEX IF NOT EXISTS stocks_active_ticker_uk ON stocks (ticker) WHERE is_active;
CREATE INDEX IF NOT EXISTS stocks_company_id_idx ON stocks (company_id);
CREATE INDEX IF NOT EXISTS stocks_security_group_idx ON stocks (security_group);

-- ── service_companies ───────────────────────────────────────────────────────
--
-- 수집 대상 목록. 비면 시세·수급·배당·재무 잡의 대상이 전부 0이 된다.
--
-- 테마를 담지 않는다. 답하는 질문이 "이 법인을 수집하는가" 하나뿐이고, 테마 소속은
-- theme_stocks 가 다대다로 이미 들고 있다. 여기에 theme_id 를 두면 두 테마에 걸친
-- 법인이 두 행이 되어 JOIN 한 번에 같은 종목을 두 번 수집한다.
CREATE TABLE IF NOT EXISTS service_companies (
    company_id BIGINT PRIMARY KEY REFERENCES companies (id) ON DELETE CASCADE,
    name       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── 시세 · 수급 · 배당 · 밸류에이션 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_candles_daily (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date  DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    source      TEXT    NOT NULL,   -- 'FDR' | 'KIS'
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS stock_candles_daily_date_idx ON stock_candles_daily (trade_date);

-- 주봉·월봉 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_candles_period (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    period      TEXT    NOT NULL,   -- 'W' | 'M'
    base_date   DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,   -- 거래량
    trade_value BIGINT,     -- 거래대금
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, period, base_date)
);

CREATE TABLE IF NOT EXISTS stock_investor_flows (
    stock_id            BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date          DATE   NOT NULL,
    individual_net_qty  BIGINT,     -- 개인순매수량
    institution_net_qty BIGINT,     -- 기관순매수량
    foreign_net_qty     BIGINT,     -- 외국인순매수량
    foreign_hold_ratio  NUMERIC,    -- 외국인보유율
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_dividends (
    listing_id  BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    record_date DATE   NOT NULL,
    divi_kind   TEXT   NOT NULL,
    dps         NUMERIC,
    pay_date    DATE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (listing_id, record_date, divi_kind)
);

CREATE TABLE IF NOT EXISTS stock_valuations_daily (
    listing_id     BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date     DATE   NOT NULL,
    market_cap     BIGINT,
    per            NUMERIC,
    pbr            NUMERIC,
    eps            NUMERIC,
    bps            NUMERIC,
    dividend_yield NUMERIC,
    r_1w           NUMERIC,
    r_1m           NUMERIC,
    r_3m           NUMERIC,
    PRIMARY KEY (listing_id, trade_date)
);

-- ── news ────────────────────────────────────────────────────────────────────
-- is_processed: 삼중항 추출 시도 완료 여부. FALSE 인 행이 extract_triples 대상.
-- relation_extracted: 삼중항이 1개 이상 나왔는지. is_processed=TRUE 일 때만 유의미.
-- cluster_rep_news_id: 같은 런에서 같은 사건(클러스터)으로 묶인 기사들의 대표 뉴스 id.
--   대표 기사와 단독 기사는 자기 자신을 가리킨다. 런 단위 정보라 런 간 병합은 없다.
CREATE TABLE IF NOT EXISTS news (
    id                  BIGSERIAL PRIMARY KEY,
    title               TEXT,
    text                TEXT,
    summary             TEXT,
    link                TEXT UNIQUE,
    originallink        TEXT,
    published_at        TIMESTAMPTZ,
    collected_at        TIMESTAMPTZ DEFAULT now(),
    is_processed        BOOLEAN NOT NULL DEFAULT FALSE,
    relation_extracted  BOOLEAN,
    cluster_rep_news_id BIGINT REFERENCES news (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_news_cluster_rep ON news (cluster_rep_news_id);
CREATE INDEX IF NOT EXISTS idx_news_unprocessed
  ON news (id) WHERE NOT is_processed;

-- ── news_companies ──────────────────────────────────────────────────────────
-- 뉴스-기업 매핑. 삼중항의 COMPANY 엔티티를 ticker → companies.id 로 해석해 적재한다.
CREATE TABLE IF NOT EXISTS news_companies (
    id         BIGSERIAL PRIMARY KEY,
    news_id    BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (news_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_news_companies_news    ON news_companies (news_id);
CREATE INDEX IF NOT EXISTS idx_news_companies_company ON news_companies (company_id);

-- ── themes ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS themes (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    -- 추출·병합된 소스 목록 (예: {judal,naver}). DAG SOURCES 우선순위 순서를 유지한다.
    sources     TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS theme_stocks (
    id       BIGSERIAL PRIMARY KEY,
    theme_id BIGINT NOT NULL REFERENCES themes (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    reason   TEXT,
    UNIQUE (theme_id, stock_id)
);

CREATE INDEX IF NOT EXISTS theme_stocks_theme_idx ON theme_stocks (theme_id);
CREATE INDEX IF NOT EXISTS theme_stocks_stock_idx ON theme_stocks (stock_id);

-- ── search_keywords ─────────────────────────────────────────────────────────
-- news_pipeline 이 네이버 뉴스 검색에 쓰는 쿼리 원천. keyword 한 행이 API 요청 한 번이며,
-- 콤마 등 네이버 검색식은 문자열 그대로 query 파라미터로 전달된다.
CREATE TABLE IF NOT EXISTS search_keywords (
    id               BIGSERIAL PRIMARY KEY,
    keyword          TEXT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_searched_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_search_keywords_last_searched
  ON search_keywords (last_searched_at);

INSERT INTO search_keywords (keyword)
VALUES
    ('특징주,공급'), ('특징주,계약'), ('특징주,수주'), ('특징주,납품')
ON CONFLICT (keyword) DO NOTHING;

-- ── disclosures ─────────────────────────────────────────────────────────────
--
-- DART 단일판매ㆍ공급계약체결 공시(정정 포함)를 접수번호 단위로 적재한다.
CREATE TABLE IF NOT EXISTS disclosures (
    -- 식별자
    id                     BIGSERIAL PRIMARY KEY,
    rcept_no               TEXT NOT NULL,

    -- 공시 주체 (제출사)
    company_id             BIGINT REFERENCES companies (id),
    corp_code              TEXT NOT NULL,
    ticker                 VARCHAR(20),
    corp_cls               TEXT,             -- 'KOSPI' | 'KOSDAQ' | 'KONEX' | 'UNLISTED'

    -- 공시 문서 메타
    report_nm              TEXT NOT NULL,
    rcept_dt               DATE NOT NULL,
    flr_nm                 TEXT,
    link                   TEXT NOT NULL,

    -- 계약 내용
    contract_type          TEXT,             -- 판매ㆍ공급계약 구분
    contract_name          TEXT,             -- 체결계약명
    order_date             DATE,             -- 계약(수주)일자 (ISO 기재만)
    start_date             DATE,             -- 계약 시작일 (ISO 기재만)
    end_date               DATE,             -- 계약 종료일 (ISO 기재만)

    -- 계약 상대방
    counterparty           TEXT,             -- 계약상대 원문 표기 (자유 텍스트)
    counterparty_corp_name TEXT,             -- 역매칭된 법인명 (companies.name)
    counterparty_corp_code TEXT,             -- 역매칭된 DART 고유번호
    counterparty_ticker    VARCHAR(20),      -- 역매칭된 종목 단축코드 (상장사만)

    -- 정정 체인
    is_correction          BOOLEAN NOT NULL DEFAULT false,
    -- 체인 루트(최초 원공시) 접수번호. 원공시는 자기 자신, 정정공시는 link job 의
    -- 재귀 해소(resolve_original_rcept_nos)가 채운다 — 원문에는 부모의 제출일만 있고
    -- 접수번호가 없어 DB 안에서만 확정할 수 있다. 원장 적재는 체인당 최신 회차 1행만
    -- 담아 disclosure_count 가 문서 수가 아니라 계약 수가 된다.
    original_rcept_no      TEXT,
    correction_target_report TEXT,           -- "정정관련 공시서류"
    correction_target_date DATE,             -- "정정관련 공시서류제출일"
    correction_reason      TEXT,             -- "정정사유"

    -- 원문/부가 데이터
    fields                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    meta                   JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- relation_sources.rcept_no FK 의 참조 대상이기도 하다 (유니크 인덱스로 충분).
CREATE UNIQUE INDEX IF NOT EXISTS disclosures_rcept_no_uk ON disclosures (rcept_no);
CREATE INDEX IF NOT EXISTS disclosures_company_id_idx ON disclosures (company_id);
CREATE INDEX IF NOT EXISTS disclosures_rcept_dt_idx ON disclosures (rcept_dt);
CREATE INDEX IF NOT EXISTS disclosures_report_nm_idx ON disclosures (report_nm);

-- 계약상대 역방향 조회("누가 이 회사에 공급하나")용. 값이 있는 행만 담는 부분 인덱스라
-- 크기가 작다. 매칭 실패(익명 기재ㆍ해외법인ㆍ모호)는 자연히 빠진다.
-- counterparty_company_id 는 승격 대상이 아니라 fields 에 남아 표현식 인덱스를 유지한다.
CREATE INDEX IF NOT EXISTS disclosures_counterparty_corp_code_idx
  ON disclosures (counterparty_corp_code) WHERE counterparty_corp_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS disclosures_counterparty_company_idx
  ON disclosures (((fields ->> 'counterparty_company_id')::bigint))
  WHERE fields ->> 'counterparty_company_id' IS NOT NULL;

-- 정정 체인 해소의 부모 탐색 경로(corp_code + rcept_dt = correction_target_date).
CREATE INDEX IF NOT EXISTS disclosures_corp_code_rcept_dt_idx
  ON disclosures (corp_code, rcept_dt);
-- 체인 단위 dedupe(원장 적재)와 "이 원공시의 회차들" 역조회.
CREATE INDEX IF NOT EXISTS disclosures_original_rcept_no_idx
  ON disclosures (original_rcept_no) WHERE original_rcept_no IS NOT NULL;

-- ── relation_sources: 근거 원장 ─────────────────────────────────────────────
-- 한 행 = (출처 1건 × 삼중항 1개). 출처는 뉴스 XOR 공시. Neo4j 간선의 근거를 전부 담는
-- 원장이며, 간선 식별은 (subject_name, relation, object_name) 자연키다 — elementId 는
-- 간선 재생성·백업 복원에 깨지지만 자연키는 불변이다.
-- 엔티티 식별은 정규명(+타입)이 기본, code(ticker/ISO)는 적재 시 사전 조회로 채우는
-- 보조 키(미상장 등 미해석이면 NULL). type 은 엔티티 확장 대비(현재 COMPANY 만).
CREATE TABLE IF NOT EXISTS relation_sources (
    id            BIGSERIAL PRIMARY KEY,

    -- 출처 (news XOR disclosure — 아래 CHECK 로 강제)
    source_type   TEXT NOT NULL CHECK (source_type IN ('news', 'disclosure')),
    news_id       BIGINT REFERENCES news (id) ON DELETE CASCADE,
    rcept_no      TEXT REFERENCES disclosures (rcept_no),

    -- 삼중항 (Neo4j 간선 자연키). relation 은 PREDICATE_DICT 의 닫힌 어휘
    -- (SUPPLIES_TO / INVESTS_IN / ACQUIRES).
    subject_name  TEXT NOT NULL,
    subject_type  VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    subject_code  VARCHAR(20),          -- COMPANY: KRX ticker. 미해석이면 NULL → 백필
    relation      VARCHAR(30) NOT NULL,
    object_name   TEXT NOT NULL,
    object_type   VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    object_code   VARCHAR(20),

    -- 근거 상세 (공통)
    evidence      TEXT,                 -- UI 노출용 자립 근거 문장
    mentioned_at  DATE NOT NULL,        -- 뉴스: 보도일 / 공시: rcept_dt
    item          TEXT,                 -- 뉴스: 추출 품목 구
                                        -- 공시: 계약명·구분 조합 — 둘 다 있으면
                                        -- "contract_type: contract_name", 아니면 있는 쪽만

    -- 뉴스 전용 (공시면 NULL)
    source_sentence TEXT,               -- 원문 문장 (verbatim)

    -- 뉴스: LLM 판정 / 공시: 확정 사실이므로 항상 affirmed + past_or_present_fact
    polarity        TEXT,               -- affirmed / denied / terminated
    tense           TEXT,               -- past_or_present_fact / future_or_planned / modal_possibility

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 출처 XOR: source_type 과 출처 키의 존재가 정확히 일치해야 한다.
    CONSTRAINT chk_relsrc_news_key       CHECK ((source_type = 'news')       = (news_id  IS NOT NULL)),
    CONSTRAINT chk_relsrc_disclosure_key CHECK ((source_type = 'disclosure') = (rcept_no IS NOT NULL)),

    -- 재추출·재적재 멱등 (ON CONFLICT DO NOTHING).
    -- NULL 은 서로 다른 값으로 취급되므로 뉴스 행은 uq_disclosure 에, 공시 행은
    -- uq_news 에 걸리지 않는다.
    CONSTRAINT uq_relsrc_news       UNIQUE (news_id,  subject_name, relation, object_name),
    CONSTRAINT uq_relsrc_disclosure UNIQUE (rcept_no, subject_name, relation, object_name)
);

-- 서빙 핵심 경로: 간선 자연키 → 근거 목록 최신순
CREATE INDEX IF NOT EXISTS idx_relsrc_edge
    ON relation_sources (subject_name, relation, object_name, mentioned_at DESC);

-- 서빙 보조 경로: 기업별 근거 조회 (code 우선, 없으면 name)
CREATE INDEX IF NOT EXISTS idx_relsrc_subject_code
    ON relation_sources (subject_code) WHERE subject_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_object_code
    ON relation_sources (object_code) WHERE object_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_subject_name ON relation_sources (subject_name);
CREATE INDEX IF NOT EXISTS idx_relsrc_object_name  ON relation_sources (object_name);

-- 출처별 역조회 ("이 뉴스/공시가 만든 관계 전부")
CREATE INDEX IF NOT EXISTS idx_relsrc_news     ON relation_sources (news_id)  WHERE news_id  IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_rcept_no ON relation_sources (rcept_no) WHERE rcept_no IS NOT NULL;

-- ── entities_relations: 간선 수준 집계 (Neo4j 간선 속성의 원천) ─────────────
-- 한 행 = 그래프 간선 하나. Neo4j 간선의 요약값은 항상 이 뷰와 대조·재작성 가능하다.
-- 조회가 무거워지면 MATERIALIZED VIEW 로 승격.
CREATE OR REPLACE VIEW entities_relations AS
SELECT subject_name, subject_type, relation, object_name, object_type,
       count(*) FILTER (WHERE source_type = 'news')       AS news_mention_count,
       count(*) FILTER (WHERE source_type = 'disclosure') AS disclosure_count,
       min(mentioned_at) AS first_mentioned_at,
       max(mentioned_at) AS last_mentioned_at,
       -- 공시 근거 배열 — Neo4j 간선에서 근거 공시(원장 rcept_no)와 계약 요약을
       -- RDB 조회 없이 바로 읽기 위한 캐시. item 이 NULL 인 행은 items 에서만
       -- 빠진다(Neo4j 리스트 속성은 null 원소 불가).
       array_agg(rcept_no ORDER BY mentioned_at, rcept_no)
           FILTER (WHERE source_type = 'disclosure')      AS disclosure_rcept_nos,
       array_agg(item ORDER BY mentioned_at, rcept_no)
           FILTER (WHERE source_type = 'disclosure' AND item IS NOT NULL)
                                                          AS disclosure_items,
       -- 뉴스 근거 배열 — 근거 뉴스(원장 news_id)와 품목 요약의 캐시. 규칙은 공시와 동일:
       -- item 이 NULL 인 행은 news_items 에서만 빠진다.
       array_agg(news_id ORDER BY mentioned_at, news_id)
           FILTER (WHERE source_type = 'news')            AS news_ids,
       array_agg(item ORDER BY mentioned_at, news_id)
           FILTER (WHERE source_type = 'news' AND item IS NOT NULL)
                                                          AS news_items
FROM relation_sources
GROUP BY 1, 2, 3, 4, 5;
