CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET timezone TO ''Asia/Seoul''', current_database());
END $$;

-- ── companies ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
    id                   BIGSERIAL PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               VARCHAR(20),
    corp_code            TEXT,
    is_listed            BOOLEAN NOT NULL,
    description          TEXT,
    description_source   TEXT,
    description_rcept_no TEXT,
    wikidata_qid         TEXT,
    ceo_name             TEXT,
    country              TEXT NOT NULL,
    industry_code        TEXT,
    established_on       DATE,
    fiscal_month         TEXT,
    homepage             TEXT,
    address              TEXT,
    delisted_at          DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_active_ticker_uk
  ON companies (ticker) WHERE delisted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_corp_code_uk
  ON companies (corp_code) WHERE corp_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_wikidata_uk
  ON companies (wikidata_qid) WHERE wikidata_qid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies (name);
CREATE INDEX IF NOT EXISTS companies_country_idx ON companies (country);

CREATE TABLE IF NOT EXISTS company_aliases (
    id         BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    alias      TEXT   NOT NULL,
    lang       TEXT,
    source     TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (alias, company_id)
);

CREATE INDEX IF NOT EXISTS company_aliases_alias_idx   ON company_aliases (alias);
CREATE INDEX IF NOT EXISTS company_aliases_company_idx ON company_aliases (company_id);

CREATE TABLE IF NOT EXISTS company_financials (
    id                BIGSERIAL PRIMARY KEY,
    company_id        BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    source            TEXT NOT NULL,
    fiscal_yymm       TEXT NOT NULL,
    period_type       TEXT NOT NULL,   -- 'A' | 'QC' | 'Q'
    fs_div            TEXT,            -- 'CFS' | 'OFS'
    disclosed_at      DATE,
    rcept_no          TEXT,
    revenue           BIGINT,
    operating_income  BIGINT,
    net_income        BIGINT,
    roe               NUMERIC,
    eps               NUMERIC,
    bps               NUMERIC,
    total_assets      BIGINT,
    total_liabilities BIGINT,
    total_equity      BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS company_financials_uk
    ON company_financials (company_id, source, fs_div, fiscal_yymm, period_type, COALESCE(rcept_no, ''));

CREATE INDEX IF NOT EXISTS company_financials_lookup_idx
    ON company_financials (company_id, period_type, fiscal_yymm DESC);

CREATE TABLE IF NOT EXISTS stocks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               TEXT NOT NULL,
    market               TEXT NOT NULL,
    company_id           BIGINT REFERENCES companies (id),
    standard_code        TEXT NOT NULL,
    listed_date          DATE,
    delisted_at          DATE,
    is_active            BOOLEAN NOT NULL DEFAULT true,
    trading_suspended    BOOLEAN NOT NULL DEFAULT false,
    under_administration BOOLEAN NOT NULL DEFAULT false,
    delisting_trade      BOOLEAN NOT NULL DEFAULT false,
    listed_shares        BIGINT,
    par_value            NUMERIC,
    capital              BIGINT,
    source               TEXT NOT NULL DEFAULT 'KIS_MASTER',
    security_group       TEXT,
    preferred_stock      BOOLEAN NOT NULL DEFAULT false,   -- 이하 3종: 법인 이관·서비스 대상 필터
    etp                  BOOLEAN NOT NULL DEFAULT false,
    spac                 BOOLEAN NOT NULL DEFAULT false,
    krx100               BOOLEAN NOT NULL DEFAULT false,
    krx300               BOOLEAN NOT NULL DEFAULT false,
    kosdaq150            BOOLEAN NOT NULL DEFAULT false,   -- KOSPI 종목은 항상 false
    inactive_at          TIMESTAMPTZ,
    raw_attributes       JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    synced_at            TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS stocks_standard_code_uk ON stocks (standard_code);
CREATE UNIQUE INDEX IF NOT EXISTS stocks_active_ticker_uk ON stocks (ticker) WHERE is_active;
CREATE INDEX IF NOT EXISTS stocks_company_id_idx ON stocks (company_id);
CREATE INDEX IF NOT EXISTS stocks_security_group_idx ON stocks (security_group);

-- ── service_companies ───────────────────────────────────────────────────────
--
-- 수집 대상 목록. 비면 시세·수급·배당·재무 잡의 대상이 전부 0이 된다.
--
-- 테마를 담지 않는다. 답하는 질문이 "이 법인을 수집하는가" 하나뿐이고, 테마 소속은
-- theme_stocks 가 다대다로 이미 들고 있다. 여기에 theme_id 를 두면 두 테마에 걸친
-- 법인이 두 행이 되어 JOIN 한 번에 같은 종목을 두 번 수집한다.
CREATE TABLE IF NOT EXISTS service_companies (
    company_id BIGINT PRIMARY KEY REFERENCES companies (id) ON DELETE CASCADE,
    name       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── 시세 · 수급 · 배당 · 밸류에이션 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_candles_daily (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date  DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    source      TEXT    NOT NULL,   -- 'FDR' | 'KIS'
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS stock_candles_daily_date_idx ON stock_candles_daily (trade_date);

-- 주봉·월봉 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_candles_period (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    period      TEXT    NOT NULL,   -- 'W' | 'M'
    base_date   DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,   -- 거래량
    trade_value BIGINT,     -- 거래대금
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, period, base_date)
);

CREATE TABLE IF NOT EXISTS stock_investor_flows (
    stock_id            BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date          DATE   NOT NULL,
    individual_net_qty  BIGINT,     -- 개인순매수량
    institution_net_qty BIGINT,     -- 기관순매수량
    foreign_net_qty     BIGINT,     -- 외국인순매수량
    foreign_hold_ratio  NUMERIC,    -- 외국인보유율
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_dividends (
    listing_id  BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    record_date DATE   NOT NULL,
    divi_kind   TEXT   NOT NULL,
    dps         NUMERIC,
    pay_date    DATE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (listing_id, record_date, divi_kind)
);

CREATE TABLE IF NOT EXISTS stock_valuations_daily (
    listing_id     BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date     DATE   NOT NULL,
    market_cap     BIGINT,
    per            NUMERIC,
    pbr            NUMERIC,
    eps            NUMERIC,
    bps            NUMERIC,
    dividend_yield NUMERIC,
    r_1w           NUMERIC,
    r_1m           NUMERIC,
    r_3m           NUMERIC,
    PRIMARY KEY (listing_id, trade_date)
);

-- ── news ────────────────────────────────────────────────────────────────────
-- triple_extracted: 삼중항 추출 상태. NULL=미시도(extract_triples 대상),
--   TRUE=삼중항 1개 이상, FALSE=시도했으나 없음. 추출 실패 시 NULL로 남아 다음 런에
--   재시도된다. 미시도는 IS NULL, 없음은 = FALSE 로 조회한다 — NOT triple_extracted 는
--   3치 논리 탓에 NULL 행을 걸러버리므로 쓰지 않는다.
-- cluster_id: 소속 클러스터(news_clusters). 배치를 넘어 같은 사건으로 판정된 기사가 같은
--   클러스터를 가리키고, 단독 기사도 자기만의 클러스터 행을 가져 조회가 균일하다.
--   news_clusters.representative_news_id 가 다시 news 를 참조하는 순환이라 이 컬럼은
--   news_clusters 뒤에서 ALTER 로 붙인다.
-- cluster_terms: 클러스터링에 쓴 이 기사의 토큰 가중치({토큰: 가중치}). 판정 신호인 검색
--   description 은 저장하지 않으므로, 이 값이 없으면 기사 벡터를 다시 만들 수 없다.
--   클러스터에 멤버가 더해질 때 대표(메도이드)를 저장 멤버 전체로 다시 고르는 데 쓴다.
CREATE TABLE IF NOT EXISTS news (
    id                  BIGSERIAL PRIMARY KEY,
    title               TEXT,
    text                TEXT,
    summary             TEXT,
    link                TEXT UNIQUE,
    originallink        TEXT,
    published_at        TIMESTAMPTZ,
    collected_at        TIMESTAMPTZ DEFAULT now(),
    triple_extracted    BOOLEAN,
    cluster_terms       JSONB
);

CREATE INDEX IF NOT EXISTS idx_news_unprocessed
  ON news (id) WHERE triple_extracted IS NULL;

-- ── news_clusters ───────────────────────────────────────────────────────────
-- 같은 사건을 다룬 기사 묶음. 수집 런마다 새 기사를 14일 이동 윈도우 안의 클러스터와
-- 비교해 합류시키거나 새 클러스터를 만든다(pipelines/news/transformers/clustering/
-- incremental.py). 클러스터당 저장 기사는 누적 cap(기본 3) 까지이고, cap 이 찬 뒤에는
-- 마지막 저장 기사와 보도일이 다른 기사만 그 날짜에 1건 더 받는다. cap 에 걸린 기사는
-- 본문을 크롤링하지 않으며 news 에도 남지 않는다.
--
-- term_weights: 판정된 모든 기사(버린 기사 포함)의 토큰 가중치 원시 합 — 다음 런이 새
--   기사와 비교하는 대상(centroid).
-- original_size: 판정된 누적 기사 수(버린 기사 포함). member_count: news 에 저장된 수.
-- first/last_published_at: 판정된 모든 기사의 보도 시각 범위. 후보 조회는
--   last_published_at 기준이라, cap 이 찬 뜨거운 사건도 기사가 이어지는 한 윈도우에 남는다.
-- representative_news_id: 대표(저장 멤버 중 메도이드). 멤버가 늘면 다시 고른다.
-- cohesion: 멤버 간 평균 코사인 유사도. keywords: term_weights 상위 토큰(표시용).
CREATE TABLE IF NOT EXISTS news_clusters (
    id                     BIGSERIAL PRIMARY KEY,
    representative_news_id BIGINT REFERENCES news (id) ON DELETE SET NULL,
    keywords               TEXT[] NOT NULL DEFAULT '{}',
    term_weights           JSONB NOT NULL DEFAULT '{}'::jsonb,
    cohesion               NUMERIC,
    original_size          INT NOT NULL DEFAULT 0,
    member_count           INT NOT NULL DEFAULT 0,
    first_published_at     TIMESTAMPTZ NOT NULL,
    last_published_at      TIMESTAMPTZ NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_news_clusters_size CHECK (member_count <= original_size)
);

CREATE INDEX IF NOT EXISTS idx_news_clusters_last_published ON news_clusters (last_published_at);

ALTER TABLE news ADD COLUMN IF NOT EXISTS cluster_id
    BIGINT REFERENCES news_clusters (id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_news_cluster ON news (cluster_id);

-- ── news_companies ──────────────────────────────────────────────────────────
-- 뉴스-기업 매핑. 삼중항의 COMPANY 엔티티를 ticker → companies.id 로 해석해 적재한다.
CREATE TABLE IF NOT EXISTS news_companies (
    id         BIGSERIAL PRIMARY KEY,
    news_id    BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (news_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_news_companies_news    ON news_companies (news_id);
CREATE INDEX IF NOT EXISTS idx_news_companies_company ON news_companies (company_id);

-- ── themes ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS themes (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT,
    -- 추출·병합된 소스 목록 (예: {judal,naver}). DAG SOURCES 우선순위 순서를 유지한다.
    sources     TEXT[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS theme_stocks (
    id       BIGSERIAL PRIMARY KEY,
    theme_id BIGINT NOT NULL REFERENCES themes (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    reason   TEXT,
    UNIQUE (theme_id, stock_id)
);

CREATE INDEX IF NOT EXISTS theme_stocks_theme_idx ON theme_stocks (theme_id);
CREATE INDEX IF NOT EXISTS theme_stocks_stock_idx ON theme_stocks (stock_id);

-- ── search_keywords ─────────────────────────────────────────────────────────
-- news_scheduled_pipeline 이 네이버 뉴스 검색에 쓰는 쿼리 원천. keyword 한 행이 API 요청 한 번이며,
-- 콤마 등 네이버 검색식은 문자열 그대로 query 파라미터로 전달된다.
CREATE TABLE IF NOT EXISTS search_keywords (
    id               BIGSERIAL PRIMARY KEY,
    keyword          TEXT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_searched_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_search_keywords_last_searched
  ON search_keywords (last_searched_at);

INSERT INTO search_keywords (keyword)
VALUES
    ('특징주,공급'), ('특징주,계약'), ('특징주,수주'), ('특징주,납품')
ON CONFLICT (keyword) DO NOTHING;

-- ── disclosures ─────────────────────────────────────────────────────────────
--
-- DART 단일판매ㆍ공급계약체결 공시(정정 포함)를 접수번호 단위로 적재한다.
CREATE TABLE IF NOT EXISTS disclosures (
    -- 식별자
    id                     BIGSERIAL PRIMARY KEY,
    rcept_no               TEXT NOT NULL,

    -- 공시 주체 (제출사)
    company_id             BIGINT REFERENCES companies (id),
    corp_code              TEXT NOT NULL,
    ticker                 VARCHAR(20),
    corp_cls               TEXT,             -- 'KOSPI' | 'KOSDAQ' | 'KONEX' | 'UNLISTED'

    -- 공시 문서 메타
    report_nm              TEXT NOT NULL,
    rcept_dt               DATE NOT NULL,
    flr_nm                 TEXT,
    link                   TEXT NOT NULL,

    -- 계약 내용
    contract_type          TEXT,             -- 판매ㆍ공급계약 구분
    contract_name          TEXT,             -- 체결계약명
    order_date             DATE,             -- 계약(수주)일자 (ISO 기재만)
    start_date             DATE,             -- 계약 시작일 (ISO 기재만)
    end_date               DATE,             -- 계약 종료일 (ISO 기재만)

    -- 계약 상대방
    counterparty           TEXT,             -- 계약상대 원문 표기 (자유 텍스트)
    counterparty_corp_name TEXT,             -- 역매칭된 법인명 (companies.name)
    counterparty_corp_code TEXT,             -- 역매칭된 DART 고유번호
    counterparty_ticker    VARCHAR(20),      -- 역매칭된 종목 단축코드 (상장사만)

    -- 정정 체인
    is_correction          BOOLEAN NOT NULL DEFAULT false,
    -- 체인 루트(최초 원공시) 접수번호. 원공시는 자기 자신, 정정공시는 link job 의
    -- 재귀 해소(resolve_original_rcept_nos)가 채운다 — 원문에는 부모의 제출일만 있고
    -- 접수번호가 없어 DB 안에서만 확정할 수 있다. 원장 적재는 체인당 최신 회차 1행만
    -- 담아 disclosure_count 가 문서 수가 아니라 계약 수가 된다.
    original_rcept_no      TEXT,
    correction_target_report TEXT,           -- "정정관련 공시서류"
    correction_target_date DATE,             -- "정정관련 공시서류제출일"
    correction_reason      TEXT,             -- "정정사유"

    -- 원문/부가 데이터
    fields                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    meta                   JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- relation_sources.rcept_no FK 의 참조 대상이기도 하다 (유니크 인덱스로 충분).
CREATE UNIQUE INDEX IF NOT EXISTS disclosures_rcept_no_uk ON disclosures (rcept_no);
CREATE INDEX IF NOT EXISTS disclosures_company_id_idx ON disclosures (company_id);
CREATE INDEX IF NOT EXISTS disclosures_rcept_dt_idx ON disclosures (rcept_dt);
CREATE INDEX IF NOT EXISTS disclosures_report_nm_idx ON disclosures (report_nm);

-- 계약상대 역방향 조회("누가 이 회사에 공급하나")용. 값이 있는 행만 담는 부분 인덱스라
-- 크기가 작다. 매칭 실패(익명 기재ㆍ해외법인ㆍ모호)는 자연히 빠진다.
-- counterparty_company_id 는 승격 대상이 아니라 fields 에 남아 표현식 인덱스를 유지한다.
CREATE INDEX IF NOT EXISTS disclosures_counterparty_corp_code_idx
  ON disclosures (counterparty_corp_code) WHERE counterparty_corp_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS disclosures_counterparty_company_idx
  ON disclosures (((fields ->> 'counterparty_company_id')::bigint))
  WHERE fields ->> 'counterparty_company_id' IS NOT NULL;

-- 정정 체인 해소의 부모 탐색 경로(corp_code + rcept_dt = correction_target_date).
CREATE INDEX IF NOT EXISTS disclosures_corp_code_rcept_dt_idx
  ON disclosures (corp_code, rcept_dt);
-- 체인 단위 dedupe(원장 적재)와 "이 원공시의 회차들" 역조회.
CREATE INDEX IF NOT EXISTS disclosures_original_rcept_no_idx
  ON disclosures (original_rcept_no) WHERE original_rcept_no IS NOT NULL;

-- ── relation_sources: 근거 원장 ─────────────────────────────────────────────
-- 한 행 = (출처 1건 × 삼중항 1개). 출처는 뉴스 XOR 공시. Neo4j 간선의 근거를 전부 담는
-- 원장이며, 간선 식별은 (subject_name, relation, object_name) 자연키다 — elementId 는
-- 간선 재생성·백업 복원에 깨지지만 자연키는 불변이다.
-- 엔티티 식별은 정규명(+타입)이 기본, code(ticker/ISO)는 적재 시 사전 조회로 채우는
-- 보조 키(미상장 등 미해석이면 NULL). type 은 엔티티 확장 대비(현재 COMPANY 만).
CREATE TABLE IF NOT EXISTS relation_sources (
    id            BIGSERIAL PRIMARY KEY,

    -- 출처 (news XOR disclosure — 아래 CHECK 로 강제)
    source_type   TEXT NOT NULL CHECK (source_type IN ('news', 'disclosure')),
    news_id       BIGINT REFERENCES news (id) ON DELETE CASCADE,
    rcept_no      TEXT REFERENCES disclosures (rcept_no),

    -- 삼중항 (Neo4j 간선 자연키). relation 은 PREDICATE_DICT 의 닫힌 어휘
    -- (SUPPLIES_TO / INVESTS_IN / ACQUIRES).
    subject_name  TEXT NOT NULL,
    subject_type  VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    subject_code  VARCHAR(20),          -- COMPANY: KRX ticker. 미해석이면 NULL → 백필
    relation      VARCHAR(30) NOT NULL,
    object_name   TEXT NOT NULL,
    object_type   VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    object_code   VARCHAR(20),

    -- 근거 상세 (공통)
    evidence      TEXT,                 -- UI 노출용 자립 근거 문장
    mentioned_at  DATE NOT NULL,        -- 뉴스: 보도일 / 공시: rcept_dt
    item          TEXT,                 -- 뉴스: 추출 품목 구
                                        -- 공시: 계약명·구분 조합 — 둘 다 있으면
                                        -- "contract_type: contract_name", 아니면 있는 쪽만

    -- 뉴스 전용 (공시면 NULL)
    source_sentence TEXT,               -- 원문 문장 (verbatim)

    -- 뉴스: LLM 판정 / 공시: 확정 사실이므로 항상 affirmed + past_or_present_fact
    polarity        TEXT,               -- affirmed / denied / terminated
    tense           TEXT,               -- past_or_present_fact / future_or_planned / modal_possibility

    -- 이벤트가 각 엔드포인트 기업에 미치는 영향 (positive / negative / neutral).
    -- 같은 이벤트라도 관점별로 다르므로(공급 체결 → 공급사 호재·수요사 중립) 양쪽을
    -- 따로 담는다. 뉴스: LLM 판정 — 기사에 그 기업의 주가 반응이 명시되면 그 방향이
    -- 우선(주가그래프와 나란히 노출), 없으면 이벤트의 펀더멘털 영향 / 공시: 상수 규칙
    -- (공급계약 체결 = subject positive · object neutral). 종목 페이지는 자기 쪽
    -- 컬럼을 CASE 로 선택한다.
    subject_impact  TEXT,               -- positive / negative / neutral
    object_impact   TEXT,               -- positive / negative / neutral

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 출처 XOR: source_type 과 출처 키의 존재가 정확히 일치해야 한다.
    CONSTRAINT chk_relsrc_news_key       CHECK ((source_type = 'news')       = (news_id  IS NOT NULL)),
    CONSTRAINT chk_relsrc_disclosure_key CHECK ((source_type = 'disclosure') = (rcept_no IS NOT NULL)),

    -- 재추출·재적재 멱등 (ON CONFLICT DO NOTHING).
    -- NULL 은 서로 다른 값으로 취급되므로 뉴스 행은 uq_disclosure 에, 공시 행은
    -- uq_news 에 걸리지 않는다.
    CONSTRAINT uq_relsrc_news       UNIQUE (news_id,  subject_name, relation, object_name),
    CONSTRAINT uq_relsrc_disclosure UNIQUE (rcept_no, subject_name, relation, object_name)
);

-- 서빙 핵심 경로: 간선 자연키 → 근거 목록 최신순
CREATE INDEX IF NOT EXISTS idx_relsrc_edge
    ON relation_sources (subject_name, relation, object_name, mentioned_at DESC);

-- 서빙 보조 경로: 기업별 근거 조회 (code 우선, 없으면 name)
CREATE INDEX IF NOT EXISTS idx_relsrc_subject_code
    ON relation_sources (subject_code) WHERE subject_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_object_code
    ON relation_sources (object_code) WHERE object_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_subject_name ON relation_sources (subject_name);
CREATE INDEX IF NOT EXISTS idx_relsrc_object_name  ON relation_sources (object_name);

-- 출처별 역조회 ("이 뉴스/공시가 만든 관계 전부")
CREATE INDEX IF NOT EXISTS idx_relsrc_news     ON relation_sources (news_id)  WHERE news_id  IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_rcept_no ON relation_sources (rcept_no) WHERE rcept_no IS NOT NULL;

-- ── entities_relations: 간선 수준 집계 (Neo4j 간선 속성의 원천) ─────────────
-- 한 행 = 그래프 간선 하나. Neo4j 간선의 요약값은 항상 이 뷰와 대조·재작성 가능하다.
-- 조회가 무거워지면 MATERIALIZED VIEW 로 승격.
CREATE OR REPLACE VIEW entities_relations AS
SELECT subject_name, subject_type, relation, object_name, object_type,
       count(*) FILTER (WHERE source_type = 'news')       AS news_mention_count,
       count(*) FILTER (WHERE source_type = 'disclosure') AS disclosure_count,
       min(mentioned_at) AS first_mentioned_at,
       max(mentioned_at) AS last_mentioned_at,
       -- 공시 근거 배열 — Neo4j 간선에서 근거 공시(원장 rcept_no)와 계약 요약을
       -- RDB 조회 없이 바로 읽기 위한 캐시. item 이 NULL 인 행은 items 에서만
       -- 빠진다(Neo4j 리스트 속성은 null 원소 불가).
       array_agg(rcept_no ORDER BY mentioned_at, rcept_no)
           FILTER (WHERE source_type = 'disclosure')      AS disclosure_rcept_nos,
       array_agg(item ORDER BY mentioned_at, rcept_no)
           FILTER (WHERE source_type = 'disclosure' AND item IS NOT NULL)
                                                          AS disclosure_items,
       -- 뉴스 근거 배열 — 근거 뉴스(원장 news_id)와 품목 요약의 캐시. 규칙은 공시와 동일:
       -- item 이 NULL 인 행은 news_items 에서만 빠진다.
       array_agg(news_id ORDER BY mentioned_at, news_id)
           FILTER (WHERE source_type = 'news')            AS news_ids,
       array_agg(item ORDER BY mentioned_at, news_id)
           FILTER (WHERE source_type = 'news' AND item IS NOT NULL)
                                                          AS news_items,
       -- 관점별 호재/악재 뉴스 건수 — 간선 요약에 "이 관계에서 A 기준 호재 n건"을
       -- 바로 얹기 위한 집계. neutral 은 (news_mention_count - positive - negative)로
       -- 유도 가능해 따로 담지 않는다.
       count(*) FILTER (WHERE source_type = 'news' AND subject_impact = 'positive')
                                                          AS subject_positive_count,
       count(*) FILTER (WHERE source_type = 'news' AND subject_impact = 'negative')
                                                          AS subject_negative_count,
       count(*) FILTER (WHERE source_type = 'news' AND object_impact = 'positive')
                                                          AS object_positive_count,
       count(*) FILTER (WHERE source_type = 'news' AND object_impact = 'negative')
                                                          AS object_negative_count
FROM relation_sources
GROUP BY 1, 2, 3, 4, 5;
