-- 종목 식별자 구조 변경: symbol PK -> surrogate id (반복 적용 안전)
--
-- 배경
--   1) candles·companies가 stocks를 FK로 참조한다. 텍스트 자연키보다 surrogate id가
--      일관되고, 비상장·외국 기업까지 담는 companies와 키 체계를 맞출 수 있다.
--   2) 종목코드는 상장폐지 후 재사용될 수 있다. PK가 symbol이면 재사용된 코드로 신규
--      상장이 들어올 때 upsert가 옛 회사 행을 덮어쓰고, 두 회사 이력이 한 행에 섞인다.
--      (FDR 상장폐지 4,170건과 현재 상장 2,872건을 대조한 실측에서 보통주 재사용은
--       관측되지 않았다. 지금 터지는 버그는 아니지만 구조적으로 막아둔다.)
--
-- upsert conflict target을 standard_code로 두는 이유
--   symbol 부분 유니크(WHERE is_active)를 conflict target으로 쓰면, 종목이 하루 master에서
--   빠졌다가 다시 나타날 때 기존 비활성 행과 충돌하지 않아 중복 행이 생긴다. 표준코드는
--   활성 여부와 무관하게 같은 종목을 가리키므로 재등장 시 같은 행을 되살린다.
--   반대로 코드가 재사용되어 다른 회사가 새 표준코드로 들어오면 새 행이 되고, 옛 행은
--   비활성 상태로 남는다 — 두 경우가 모두 의도대로 갈린다.
--
-- 주의: stocks에 표준코드가 중복된 행이 이미 있으면 아래 UNIQUE 생성이 실패한다.
--       조용히 넘어가는 것보다 실패하는 편이 낫다. 실패하면 중복부터 정리한다.

-- 1) surrogate id
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

-- 2) PK를 symbol -> id 로 교체
DO $$
DECLARE
  pk_cols text[];
BEGIN
  SELECT array_agg(a.attname ORDER BY a.attnum)
    INTO pk_cols
    FROM pg_constraint c
    JOIN pg_attribute a
      ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
   WHERE c.conrelid = 'stocks'::regclass
     AND c.contype = 'p';

  IF pk_cols = ARRAY['symbol'] THEN
    ALTER TABLE stocks DROP CONSTRAINT stocks_pkey;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'stocks'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE stocks ADD CONSTRAINT stocks_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- 3) 표준코드는 종목 고유 식별자. upsert conflict target.
CREATE UNIQUE INDEX IF NOT EXISTS stocks_standard_code_uk
  ON stocks (standard_code);

-- 4) 활성 종목 중에서만 단축코드가 유일하다.
--    상장폐지된 옛 행은 같은 symbol을 그대로 갖고 남을 수 있다.
CREATE UNIQUE INDEX IF NOT EXISTS stocks_active_symbol_uk
  ON stocks (symbol) WHERE is_active;

-- 5) 기업 마스터 연결 (SCRUM-50에서 채운다)
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES companies (id);
CREATE INDEX IF NOT EXISTS stocks_company_id_idx ON stocks (company_id);
