// us.json에서 생성됨 — 직접 수정하지 말 것.
// 재생성: uv run python scripts/gen_us_companies_cypher.py

// NASDAQ 102개
// [1] 한글명 변경 — ticker 로 찾아 name 만 교체. [2] 보다 먼저 와야 한다(KRX 시드와 같은 순서)
UNWIND [
  {ticker: "ADBE", name: "Adobe Inc.", kr_name: "어도비", market: "NASDAQ", sp500: true},
  {ticker: "AMD", name: "Advanced Micro Devices", kr_name: "AMD", market: "NASDAQ", sp500: true},
  {ticker: "ABNB", name: "Airbnb", kr_name: "에어비앤비", market: "NASDAQ", sp500: true},
  {ticker: "ALNY", name: "Alnylam Pharmaceuticals", kr_name: "앨나일램 파머슈티컬스", market: "NASDAQ", sp500: false},
  {ticker: "GOOGL", name: "Alphabet Inc. (Class A)", kr_name: "알파벳 A", market: "NASDAQ", sp500: true},
  {ticker: "AMZN", name: "Amazon", kr_name: "아마존닷컴", market: "NASDAQ", sp500: true},
  {ticker: "AEP", name: "American Electric Power", kr_name: "아메리칸 일렉트릭 파워", market: "NASDAQ", sp500: true},
  {ticker: "AMGN", name: "Amgen", kr_name: "암젠", market: "NASDAQ", sp500: true},
  {ticker: "ADI", name: "Analog Devices", kr_name: "애널로그 디바이시스", market: "NASDAQ", sp500: true},
  {ticker: "AAPL", name: "Apple Inc.", kr_name: "애플", market: "NASDAQ", sp500: true},
  {ticker: "AMAT", name: "Applied Materials", kr_name: "어플라이드 머티어리얼즈", market: "NASDAQ", sp500: true},
  {ticker: "APP", name: "AppLovin", kr_name: "앱러빈", market: "NASDAQ", sp500: true},
  {ticker: "ARM", name: "Arm Holdings", kr_name: "에이알엠 홀딩스(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "ASML", name: "ASML Holding", kr_name: "ASML 홀딩(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "ALAB", name: "Astera Labs", kr_name: "아스테라 랩스", market: "NASDAQ", sp500: false},
  {ticker: "ADSK", name: "Autodesk", kr_name: "오토데스크", market: "NASDAQ", sp500: true},
  {ticker: "ADP", name: "Automatic Data Processing", kr_name: "오토매틱 데이터 프로세싱", market: "NASDAQ", sp500: true},
  {ticker: "AXON", name: "Axon Enterprise", kr_name: "액손 엔터프라이즈", market: "NASDAQ", sp500: true},
  {ticker: "BKR", name: "Baker Hughes", kr_name: "베이커 휴즈", market: "NASDAQ", sp500: true},
  {ticker: "BKNG", name: "Booking Holdings", kr_name: "부킹", market: "NASDAQ", sp500: true},
  {ticker: "AVGO", name: "Broadcom", kr_name: "브로드컴", market: "NASDAQ", sp500: true},
  {ticker: "CDNS", name: "Cadence Design Systems", kr_name: "케이던스 디자인 시스템즈", market: "NASDAQ", sp500: true},
  {ticker: "CTAS", name: "Cintas", kr_name: "신타스", market: "NASDAQ", sp500: true},
  {ticker: "CSCO", name: "Cisco", kr_name: "시스코 시스템즈", market: "NASDAQ", sp500: true},
  {ticker: "CCEP", name: "Coca-Cola Europacific Partners", kr_name: "코카콜라 유로퍼시픽 파트너스", market: "NASDAQ", sp500: false},
  {ticker: "CMCSA", name: "Comcast", kr_name: "컴캐스트", market: "NASDAQ", sp500: true},
  {ticker: "CEG", name: "Constellation Energy", kr_name: "컨스털레이션 에너지", market: "NASDAQ", sp500: true},
  {ticker: "CPRT", name: "Copart", kr_name: "코파트", market: "NASDAQ", sp500: true},
  {ticker: "CRWV", name: "CoreWeave", kr_name: "코어위브", market: "NASDAQ", sp500: false},
  {ticker: "COST", name: "Costco", kr_name: "코스트코 홀세일", market: "NASDAQ", sp500: true},
  {ticker: "CRWD", name: "CrowdStrike", kr_name: "크라우드스트라이크", market: "NASDAQ", sp500: true},
  {ticker: "CSX", name: "CSX Corporation", kr_name: "CSX", market: "NASDAQ", sp500: true},
  {ticker: "DDOG", name: "Datadog", kr_name: "데이터도그", market: "NASDAQ", sp500: true},
  {ticker: "DXCM", name: "DexCom", kr_name: "덱스컴", market: "NASDAQ", sp500: true},
  {ticker: "FANG", name: "Diamondback Energy", kr_name: "다이아몬드백 에너지", market: "NASDAQ", sp500: true},
  {ticker: "DASH", name: "DoorDash", kr_name: "도어대시", market: "NASDAQ", sp500: true},
  {ticker: "EA", name: "Electronic Arts", kr_name: "일렉트로닉 아츠", market: "NASDAQ", sp500: true},
  {ticker: "EXC", name: "Exelon", kr_name: "엑셀론", market: "NASDAQ", sp500: true},
  {ticker: "FAST", name: "Fastenal", kr_name: "패스널", market: "NASDAQ", sp500: true},
  {ticker: "FER", name: "Ferrovial", kr_name: "페로비알", market: "NASDAQ", sp500: false},
  {ticker: "FTNT", name: "Fortinet", kr_name: "포티넷", market: "NASDAQ", sp500: true},
  {ticker: "GEHC", name: "GE HealthCare", kr_name: "GE 헬스케어 테크놀로지스", market: "NASDAQ", sp500: true},
  {ticker: "GILD", name: "Gilead Sciences", kr_name: "길리어드 사이언스", market: "NASDAQ", sp500: true},
  {ticker: "HONA", name: "Honeywell Aerospace", kr_name: "허니웰에어로스페이스", market: "NASDAQ", sp500: true},
  {ticker: "HON", name: "Honeywell Technologies", kr_name: "허니웰 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "IDXX", name: "Idexx Laboratories", kr_name: "아이덱스 래버러토리스", market: "NASDAQ", sp500: true},
  {ticker: "INTC", name: "Intel", kr_name: "인텔", market: "NASDAQ", sp500: true},
  {ticker: "INTU", name: "Intuit", kr_name: "인튜이트", market: "NASDAQ", sp500: true},
  {ticker: "ISRG", name: "Intuitive Surgical", kr_name: "인튜이티브 서지컬", market: "NASDAQ", sp500: true},
  {ticker: "KDP", name: "Keurig Dr Pepper", kr_name: "큐리그 닥터 페퍼", market: "NASDAQ", sp500: true},
  {ticker: "KLAC", name: "KLA Corporation", kr_name: "KLA", market: "NASDAQ", sp500: true},
  {ticker: "KHC", name: "Kraft Heinz", kr_name: "크래프트 하인즈", market: "NASDAQ", sp500: true},
  {ticker: "LRCX", name: "Lam Research", kr_name: "램 리서치", market: "NASDAQ", sp500: true},
  {ticker: "LIN", name: "Linde plc", kr_name: "린데", market: "NASDAQ", sp500: true},
  {ticker: "LITE", name: "Lumentum", kr_name: "루멘텀", market: "NASDAQ", sp500: true},
  {ticker: "MAR", name: "Marriott International", kr_name: "메리어트 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "MRVL", name: "Marvell Technology", kr_name: "마블 테크놀로지 그룹", market: "NASDAQ", sp500: true},
  {ticker: "MELI", name: "Mercado Libre", kr_name: "메르카도리브레", market: "NASDAQ", sp500: false},
  {ticker: "META", name: "Meta Platforms", kr_name: "메타 플랫폼스(페이스북)", market: "NASDAQ", sp500: true},
  {ticker: "MCHP", name: "Microchip Technology", kr_name: "마이크로칩 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "MU", name: "Micron Technology", kr_name: "마이크론 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "MSFT", name: "Microsoft", kr_name: "마이크로소프트", market: "NASDAQ", sp500: true},
  {ticker: "MSTR", name: "MicroStrategy", kr_name: "스트래티지", market: "NASDAQ", sp500: false},
  {ticker: "MDLZ", name: "Mondelez International", kr_name: "몬덜리즈 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "MPWR", name: "Monolithic Power Systems", kr_name: "모놀리식 파워 시스템", market: "NASDAQ", sp500: true},
  {ticker: "MNST", name: "Monster Beverage", kr_name: "몬스터 베버리지", market: "NASDAQ", sp500: true},
  {ticker: "NBIS", name: "Nebius Group", kr_name: "네비우스 그룹", market: "NASDAQ", sp500: false},
  {ticker: "NFLX", name: "Netflix, Inc.", kr_name: "넷플릭스", market: "NASDAQ", sp500: true},
  {ticker: "NVDA", name: "Nvidia", kr_name: "엔비디아", market: "NASDAQ", sp500: true},
  {ticker: "NXPI", name: "NXP Semiconductors", kr_name: "NXP 세미컨덕터스", market: "NASDAQ", sp500: true},
  {ticker: "ORLY", name: "O'Reilly Automotive", kr_name: "오릴리 오토모티브", market: "NASDAQ", sp500: true},
  {ticker: "ODFL", name: "Old Dominion Freight Line", kr_name: "올드 도미니언 프레이트 라인", market: "NASDAQ", sp500: true},
  {ticker: "PCAR", name: "Paccar", kr_name: "파카", market: "NASDAQ", sp500: true},
  {ticker: "PLTR", name: "Palantir Technologies", kr_name: "팔란티어", market: "NASDAQ", sp500: true},
  {ticker: "PANW", name: "Palo Alto Networks", kr_name: "팰로 앨토 네트웍스", market: "NASDAQ", sp500: true},
  {ticker: "PAYX", name: "Paychex", kr_name: "페이첵스", market: "NASDAQ", sp500: true},
  {ticker: "PYPL", name: "PayPal", kr_name: "페이팔", market: "NASDAQ", sp500: true},
  {ticker: "PDD", name: "PDD Holdings", kr_name: "핀둬둬(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "PEP", name: "PepsiCo", kr_name: "펩시코", market: "NASDAQ", sp500: true},
  {ticker: "QCOM", name: "Qualcomm", kr_name: "퀄컴", market: "NASDAQ", sp500: true},
  {ticker: "REGN", name: "Regeneron Pharmaceuticals", kr_name: "리제네론 파머슈티컬스", market: "NASDAQ", sp500: true},
  {ticker: "RKLB", name: "Rocket Lab", kr_name: "로켓 랩", market: "NASDAQ", sp500: false},
  {ticker: "ROP", name: "Roper Technologies", kr_name: "로퍼 테크놀로지스", market: "NASDAQ", sp500: true},
  {ticker: "ROST", name: "Ross Stores", kr_name: "로스 스토어스", market: "NASDAQ", sp500: true},
  {ticker: "SNDK", name: "Sandisk", kr_name: "샌디스크", market: "NASDAQ", sp500: true},
  {ticker: "STX", name: "Seagate Technology", kr_name: "시게이트 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "SHOP", name: "Shopify", kr_name: "쇼피파이", market: "NASDAQ", sp500: false},
  {ticker: "SPCX", name: "SpaceX", kr_name: "스페이스X", market: "NASDAQ", sp500: false},
  {ticker: "SBUX", name: "Starbucks", kr_name: "스타벅스", market: "NASDAQ", sp500: true},
  {ticker: "SNPS", name: "Synopsys", kr_name: "시놉시스", market: "NASDAQ", sp500: true},
  {ticker: "TMUS", name: "T-Mobile US", kr_name: "T 모바일 US", market: "NASDAQ", sp500: true},
  {ticker: "TTWO", name: "Take-Two Interactive", kr_name: "테이크 투 인터랙티브 소프트웨어", market: "NASDAQ", sp500: true},
  {ticker: "TER", name: "Teradyne", kr_name: "테라다인", market: "NASDAQ", sp500: true},
  {ticker: "TSLA", name: "Tesla, Inc.", kr_name: "테슬라", market: "NASDAQ", sp500: true},
  {ticker: "TXN", name: "Texas Instruments", kr_name: "텍사스 인스트루먼츠", market: "NASDAQ", sp500: true},
  {ticker: "TRI", name: "Thomson Reuters", kr_name: "톰슨 로이터", market: "NASDAQ", sp500: false},
  {ticker: "VRTX", name: "Vertex Pharmaceuticals", kr_name: "버텍스 파머슈티컬", market: "NASDAQ", sp500: true},
  {ticker: "WMT", name: "Walmart", kr_name: "월마트", market: "NASDAQ", sp500: true},
  {ticker: "WBD", name: "Warner Bros. Discovery", kr_name: "워너 브로스 디스커버리", market: "NASDAQ", sp500: true},
  {ticker: "WDC", name: "Western Digital", kr_name: "웨스턴 디지털", market: "NASDAQ", sp500: true},
  {ticker: "WDAY", name: "Workday, Inc.", kr_name: "워크데이", market: "NASDAQ", sp500: true},
  {ticker: "XEL", name: "Xcel Energy", kr_name: "엑셀 에너지", market: "NASDAQ", sp500: true}
] AS row
MATCH (old:Company {ticker: row.ticker})
WHERE old.name <> row.kr_name
SET old.name = row.kr_name;

// [2] name 키 MERGE — 삼중항이 만든 {name: kr_name, ticker: null} 노드를 흡수해 간선을
//     보존한다. 없으면 새로 만든다. 두 번째 기동부터는 같은 값을 다시 SET 하는 no-op
UNWIND [
  {ticker: "ADBE", name: "Adobe Inc.", kr_name: "어도비", market: "NASDAQ", sp500: true},
  {ticker: "AMD", name: "Advanced Micro Devices", kr_name: "AMD", market: "NASDAQ", sp500: true},
  {ticker: "ABNB", name: "Airbnb", kr_name: "에어비앤비", market: "NASDAQ", sp500: true},
  {ticker: "ALNY", name: "Alnylam Pharmaceuticals", kr_name: "앨나일램 파머슈티컬스", market: "NASDAQ", sp500: false},
  {ticker: "GOOGL", name: "Alphabet Inc. (Class A)", kr_name: "알파벳 A", market: "NASDAQ", sp500: true},
  {ticker: "AMZN", name: "Amazon", kr_name: "아마존닷컴", market: "NASDAQ", sp500: true},
  {ticker: "AEP", name: "American Electric Power", kr_name: "아메리칸 일렉트릭 파워", market: "NASDAQ", sp500: true},
  {ticker: "AMGN", name: "Amgen", kr_name: "암젠", market: "NASDAQ", sp500: true},
  {ticker: "ADI", name: "Analog Devices", kr_name: "애널로그 디바이시스", market: "NASDAQ", sp500: true},
  {ticker: "AAPL", name: "Apple Inc.", kr_name: "애플", market: "NASDAQ", sp500: true},
  {ticker: "AMAT", name: "Applied Materials", kr_name: "어플라이드 머티어리얼즈", market: "NASDAQ", sp500: true},
  {ticker: "APP", name: "AppLovin", kr_name: "앱러빈", market: "NASDAQ", sp500: true},
  {ticker: "ARM", name: "Arm Holdings", kr_name: "에이알엠 홀딩스(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "ASML", name: "ASML Holding", kr_name: "ASML 홀딩(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "ALAB", name: "Astera Labs", kr_name: "아스테라 랩스", market: "NASDAQ", sp500: false},
  {ticker: "ADSK", name: "Autodesk", kr_name: "오토데스크", market: "NASDAQ", sp500: true},
  {ticker: "ADP", name: "Automatic Data Processing", kr_name: "오토매틱 데이터 프로세싱", market: "NASDAQ", sp500: true},
  {ticker: "AXON", name: "Axon Enterprise", kr_name: "액손 엔터프라이즈", market: "NASDAQ", sp500: true},
  {ticker: "BKR", name: "Baker Hughes", kr_name: "베이커 휴즈", market: "NASDAQ", sp500: true},
  {ticker: "BKNG", name: "Booking Holdings", kr_name: "부킹", market: "NASDAQ", sp500: true},
  {ticker: "AVGO", name: "Broadcom", kr_name: "브로드컴", market: "NASDAQ", sp500: true},
  {ticker: "CDNS", name: "Cadence Design Systems", kr_name: "케이던스 디자인 시스템즈", market: "NASDAQ", sp500: true},
  {ticker: "CTAS", name: "Cintas", kr_name: "신타스", market: "NASDAQ", sp500: true},
  {ticker: "CSCO", name: "Cisco", kr_name: "시스코 시스템즈", market: "NASDAQ", sp500: true},
  {ticker: "CCEP", name: "Coca-Cola Europacific Partners", kr_name: "코카콜라 유로퍼시픽 파트너스", market: "NASDAQ", sp500: false},
  {ticker: "CMCSA", name: "Comcast", kr_name: "컴캐스트", market: "NASDAQ", sp500: true},
  {ticker: "CEG", name: "Constellation Energy", kr_name: "컨스털레이션 에너지", market: "NASDAQ", sp500: true},
  {ticker: "CPRT", name: "Copart", kr_name: "코파트", market: "NASDAQ", sp500: true},
  {ticker: "CRWV", name: "CoreWeave", kr_name: "코어위브", market: "NASDAQ", sp500: false},
  {ticker: "COST", name: "Costco", kr_name: "코스트코 홀세일", market: "NASDAQ", sp500: true},
  {ticker: "CRWD", name: "CrowdStrike", kr_name: "크라우드스트라이크", market: "NASDAQ", sp500: true},
  {ticker: "CSX", name: "CSX Corporation", kr_name: "CSX", market: "NASDAQ", sp500: true},
  {ticker: "DDOG", name: "Datadog", kr_name: "데이터도그", market: "NASDAQ", sp500: true},
  {ticker: "DXCM", name: "DexCom", kr_name: "덱스컴", market: "NASDAQ", sp500: true},
  {ticker: "FANG", name: "Diamondback Energy", kr_name: "다이아몬드백 에너지", market: "NASDAQ", sp500: true},
  {ticker: "DASH", name: "DoorDash", kr_name: "도어대시", market: "NASDAQ", sp500: true},
  {ticker: "EA", name: "Electronic Arts", kr_name: "일렉트로닉 아츠", market: "NASDAQ", sp500: true},
  {ticker: "EXC", name: "Exelon", kr_name: "엑셀론", market: "NASDAQ", sp500: true},
  {ticker: "FAST", name: "Fastenal", kr_name: "패스널", market: "NASDAQ", sp500: true},
  {ticker: "FER", name: "Ferrovial", kr_name: "페로비알", market: "NASDAQ", sp500: false},
  {ticker: "FTNT", name: "Fortinet", kr_name: "포티넷", market: "NASDAQ", sp500: true},
  {ticker: "GEHC", name: "GE HealthCare", kr_name: "GE 헬스케어 테크놀로지스", market: "NASDAQ", sp500: true},
  {ticker: "GILD", name: "Gilead Sciences", kr_name: "길리어드 사이언스", market: "NASDAQ", sp500: true},
  {ticker: "HONA", name: "Honeywell Aerospace", kr_name: "허니웰에어로스페이스", market: "NASDAQ", sp500: true},
  {ticker: "HON", name: "Honeywell Technologies", kr_name: "허니웰 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "IDXX", name: "Idexx Laboratories", kr_name: "아이덱스 래버러토리스", market: "NASDAQ", sp500: true},
  {ticker: "INTC", name: "Intel", kr_name: "인텔", market: "NASDAQ", sp500: true},
  {ticker: "INTU", name: "Intuit", kr_name: "인튜이트", market: "NASDAQ", sp500: true},
  {ticker: "ISRG", name: "Intuitive Surgical", kr_name: "인튜이티브 서지컬", market: "NASDAQ", sp500: true},
  {ticker: "KDP", name: "Keurig Dr Pepper", kr_name: "큐리그 닥터 페퍼", market: "NASDAQ", sp500: true},
  {ticker: "KLAC", name: "KLA Corporation", kr_name: "KLA", market: "NASDAQ", sp500: true},
  {ticker: "KHC", name: "Kraft Heinz", kr_name: "크래프트 하인즈", market: "NASDAQ", sp500: true},
  {ticker: "LRCX", name: "Lam Research", kr_name: "램 리서치", market: "NASDAQ", sp500: true},
  {ticker: "LIN", name: "Linde plc", kr_name: "린데", market: "NASDAQ", sp500: true},
  {ticker: "LITE", name: "Lumentum", kr_name: "루멘텀", market: "NASDAQ", sp500: true},
  {ticker: "MAR", name: "Marriott International", kr_name: "메리어트 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "MRVL", name: "Marvell Technology", kr_name: "마블 테크놀로지 그룹", market: "NASDAQ", sp500: true},
  {ticker: "MELI", name: "Mercado Libre", kr_name: "메르카도리브레", market: "NASDAQ", sp500: false},
  {ticker: "META", name: "Meta Platforms", kr_name: "메타 플랫폼스(페이스북)", market: "NASDAQ", sp500: true},
  {ticker: "MCHP", name: "Microchip Technology", kr_name: "마이크로칩 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "MU", name: "Micron Technology", kr_name: "마이크론 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "MSFT", name: "Microsoft", kr_name: "마이크로소프트", market: "NASDAQ", sp500: true},
  {ticker: "MSTR", name: "MicroStrategy", kr_name: "스트래티지", market: "NASDAQ", sp500: false},
  {ticker: "MDLZ", name: "Mondelez International", kr_name: "몬덜리즈 인터내셔널", market: "NASDAQ", sp500: true},
  {ticker: "MPWR", name: "Monolithic Power Systems", kr_name: "모놀리식 파워 시스템", market: "NASDAQ", sp500: true},
  {ticker: "MNST", name: "Monster Beverage", kr_name: "몬스터 베버리지", market: "NASDAQ", sp500: true},
  {ticker: "NBIS", name: "Nebius Group", kr_name: "네비우스 그룹", market: "NASDAQ", sp500: false},
  {ticker: "NFLX", name: "Netflix, Inc.", kr_name: "넷플릭스", market: "NASDAQ", sp500: true},
  {ticker: "NVDA", name: "Nvidia", kr_name: "엔비디아", market: "NASDAQ", sp500: true},
  {ticker: "NXPI", name: "NXP Semiconductors", kr_name: "NXP 세미컨덕터스", market: "NASDAQ", sp500: true},
  {ticker: "ORLY", name: "O'Reilly Automotive", kr_name: "오릴리 오토모티브", market: "NASDAQ", sp500: true},
  {ticker: "ODFL", name: "Old Dominion Freight Line", kr_name: "올드 도미니언 프레이트 라인", market: "NASDAQ", sp500: true},
  {ticker: "PCAR", name: "Paccar", kr_name: "파카", market: "NASDAQ", sp500: true},
  {ticker: "PLTR", name: "Palantir Technologies", kr_name: "팔란티어", market: "NASDAQ", sp500: true},
  {ticker: "PANW", name: "Palo Alto Networks", kr_name: "팰로 앨토 네트웍스", market: "NASDAQ", sp500: true},
  {ticker: "PAYX", name: "Paychex", kr_name: "페이첵스", market: "NASDAQ", sp500: true},
  {ticker: "PYPL", name: "PayPal", kr_name: "페이팔", market: "NASDAQ", sp500: true},
  {ticker: "PDD", name: "PDD Holdings", kr_name: "핀둬둬(ADR)", market: "NASDAQ", sp500: false},
  {ticker: "PEP", name: "PepsiCo", kr_name: "펩시코", market: "NASDAQ", sp500: true},
  {ticker: "QCOM", name: "Qualcomm", kr_name: "퀄컴", market: "NASDAQ", sp500: true},
  {ticker: "REGN", name: "Regeneron Pharmaceuticals", kr_name: "리제네론 파머슈티컬스", market: "NASDAQ", sp500: true},
  {ticker: "RKLB", name: "Rocket Lab", kr_name: "로켓 랩", market: "NASDAQ", sp500: false},
  {ticker: "ROP", name: "Roper Technologies", kr_name: "로퍼 테크놀로지스", market: "NASDAQ", sp500: true},
  {ticker: "ROST", name: "Ross Stores", kr_name: "로스 스토어스", market: "NASDAQ", sp500: true},
  {ticker: "SNDK", name: "Sandisk", kr_name: "샌디스크", market: "NASDAQ", sp500: true},
  {ticker: "STX", name: "Seagate Technology", kr_name: "시게이트 테크놀로지", market: "NASDAQ", sp500: true},
  {ticker: "SHOP", name: "Shopify", kr_name: "쇼피파이", market: "NASDAQ", sp500: false},
  {ticker: "SPCX", name: "SpaceX", kr_name: "스페이스X", market: "NASDAQ", sp500: false},
  {ticker: "SBUX", name: "Starbucks", kr_name: "스타벅스", market: "NASDAQ", sp500: true},
  {ticker: "SNPS", name: "Synopsys", kr_name: "시놉시스", market: "NASDAQ", sp500: true},
  {ticker: "TMUS", name: "T-Mobile US", kr_name: "T 모바일 US", market: "NASDAQ", sp500: true},
  {ticker: "TTWO", name: "Take-Two Interactive", kr_name: "테이크 투 인터랙티브 소프트웨어", market: "NASDAQ", sp500: true},
  {ticker: "TER", name: "Teradyne", kr_name: "테라다인", market: "NASDAQ", sp500: true},
  {ticker: "TSLA", name: "Tesla, Inc.", kr_name: "테슬라", market: "NASDAQ", sp500: true},
  {ticker: "TXN", name: "Texas Instruments", kr_name: "텍사스 인스트루먼츠", market: "NASDAQ", sp500: true},
  {ticker: "TRI", name: "Thomson Reuters", kr_name: "톰슨 로이터", market: "NASDAQ", sp500: false},
  {ticker: "VRTX", name: "Vertex Pharmaceuticals", kr_name: "버텍스 파머슈티컬", market: "NASDAQ", sp500: true},
  {ticker: "WMT", name: "Walmart", kr_name: "월마트", market: "NASDAQ", sp500: true},
  {ticker: "WBD", name: "Warner Bros. Discovery", kr_name: "워너 브로스 디스커버리", market: "NASDAQ", sp500: true},
  {ticker: "WDC", name: "Western Digital", kr_name: "웨스턴 디지털", market: "NASDAQ", sp500: true},
  {ticker: "WDAY", name: "Workday, Inc.", kr_name: "워크데이", market: "NASDAQ", sp500: true},
  {ticker: "XEL", name: "Xcel Energy", kr_name: "엑셀 에너지", market: "NASDAQ", sp500: true}
] AS row
MERGE (c:Company {name: row.kr_name})
SET c:NASDAQ,
    c.ticker = row.ticker,
    c.en_name = row.name,
    c.is_listed = true,
    c.market = row.market,
    c.sp500 = row.sp500
REMOVE c:NYSE, c.kr_name;

// NYSE 415개
// [1] 한글명 변경 — ticker 로 찾아 name 만 교체. [2] 보다 먼저 와야 한다(KRX 시드와 같은 순서)
UNWIND [
  {ticker: "MMM", name: "3M", kr_name: "3M", market: "NYSE", sp500: true},
  {ticker: "AOS", name: "A. O. Smith", kr_name: "A O 스미스", market: "NYSE", sp500: true},
  {ticker: "ABT", name: "Abbott Laboratories", kr_name: "애보트 래브러토리스", market: "NYSE", sp500: true},
  {ticker: "ABBV", name: "AbbVie", kr_name: "애브비", market: "NYSE", sp500: true},
  {ticker: "ACN", name: "Accenture", kr_name: "액센추어", market: "NYSE", sp500: true},
  {ticker: "AES", name: "AES Corporation", kr_name: "AES", market: "NYSE", sp500: true},
  {ticker: "AFL", name: "Aflac", kr_name: "애플랙", market: "NYSE", sp500: true},
  {ticker: "A", name: "Agilent Technologies", kr_name: "애질런트 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "APD", name: "Air Products", kr_name: "에어 프라덕츠 앤드 케미컬스", market: "NYSE", sp500: true},
  {ticker: "AKAM", name: "Akamai Technologies", kr_name: "아카마이 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "ALB", name: "Albemarle Corporation", kr_name: "알버말", market: "NYSE", sp500: true},
  {ticker: "ARE", name: "Alexandria Real Estate Equities", kr_name: "알렉산드리아 리얼 에스테이트 에퀴티스", market: "NYSE", sp500: true},
  {ticker: "ALGN", name: "Align Technology", kr_name: "얼라인 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "ALLE", name: "Allegion", kr_name: "얼리지언", market: "NYSE", sp500: true},
  {ticker: "LNT", name: "Alliant Energy", kr_name: "얼라이언트 에너지", market: "NYSE", sp500: true},
  {ticker: "ALL", name: "Allstate", kr_name: "올스테이트", market: "NYSE", sp500: true},
  {ticker: "MO", name: "Altria", kr_name: "알트리아 그룹", market: "NYSE", sp500: true},
  {ticker: "AMCR", name: "Amcor", kr_name: "앰코", market: "NYSE", sp500: true},
  {ticker: "AEE", name: "Ameren", kr_name: "애머런", market: "NYSE", sp500: true},
  {ticker: "AXP", name: "American Express", kr_name: "아메리칸 엑스프레스", market: "NYSE", sp500: true},
  {ticker: "AIG", name: "American International Group", kr_name: "아메리칸 인터내셔널 그룹", market: "NYSE", sp500: true},
  {ticker: "AMT", name: "American Tower", kr_name: "아메리칸 타워", market: "NYSE", sp500: true},
  {ticker: "AWK", name: "American Water Works", kr_name: "아메리칸 워터 웍스", market: "NYSE", sp500: true},
  {ticker: "AMP", name: "Ameriprise Financial", kr_name: "어메리프라이즈 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "AME", name: "Ametek", kr_name: "아메텍", market: "NYSE", sp500: true},
  {ticker: "APH", name: "Amphenol", kr_name: "암페놀", market: "NYSE", sp500: true},
  {ticker: "AON", name: "Aon plc", kr_name: "에이온", market: "NYSE", sp500: true},
  {ticker: "APA", name: "APA Corporation", kr_name: "APA", market: "NYSE", sp500: true},
  {ticker: "APO", name: "Apollo Global Management", kr_name: "아폴로 글로벌 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "APTV", name: "Aptiv", kr_name: "앱티브", market: "NYSE", sp500: true},
  {ticker: "ACGL", name: "Arch Capital Group", kr_name: "아치 캐피털 그룹", market: "NYSE", sp500: true},
  {ticker: "ADM", name: "Archer Daniels Midland", kr_name: "아처 대니얼스 미들랜드", market: "NYSE", sp500: true},
  {ticker: "ARES", name: "Ares Management", kr_name: "아레스 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "ANET", name: "Arista Networks", kr_name: "아리스타 네트웍스", market: "NYSE", sp500: true},
  {ticker: "AJG", name: "Arthur J. Gallagher & Co.", kr_name: "아서 갤러거 앤드 컴퍼니", market: "NYSE", sp500: true},
  {ticker: "AIZ", name: "Assurant", kr_name: "어슈런트", market: "NYSE", sp500: true},
  {ticker: "T", name: "AT&T", kr_name: "AT&T", market: "NYSE", sp500: true},
  {ticker: "ATO", name: "Atmos Energy", kr_name: "애트모스 에너지", market: "NYSE", sp500: true},
  {ticker: "AZO", name: "AutoZone", kr_name: "오토존", market: "NYSE", sp500: true},
  {ticker: "AVB", name: "AvalonBay Communities", kr_name: "아발론베이 커뮤니티스", market: "NYSE", sp500: true},
  {ticker: "AVY", name: "Avery Dennison", kr_name: "에이버리 데니슨", market: "NYSE", sp500: true},
  {ticker: "BALL", name: "Ball Corporation", kr_name: "볼", market: "NYSE", sp500: true},
  {ticker: "BAC", name: "Bank of America", kr_name: "뱅크오브아메리카", market: "NYSE", sp500: true},
  {ticker: "BAX", name: "Baxter International", kr_name: "박스터 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "BDX", name: "Becton Dickinson", kr_name: "벡턴 디킨슨", market: "NYSE", sp500: true},
  {ticker: "BRK.B", name: "Berkshire Hathaway", kr_name: "버크셔 해서웨이 B", market: "NYSE", sp500: true},
  {ticker: "BBY", name: "Best Buy", kr_name: "베스트 바이", market: "NYSE", sp500: true},
  {ticker: "TECH", name: "Bio-Techne", kr_name: "바이오 테크네", market: "NYSE", sp500: true},
  {ticker: "BIIB", name: "Biogen", kr_name: "바이오젠", market: "NYSE", sp500: true},
  {ticker: "BLK", name: "BlackRock", kr_name: "블랙록", market: "NYSE", sp500: true},
  {ticker: "BX", name: "Blackstone Inc.", kr_name: "블랙스톤", market: "NYSE", sp500: true},
  {ticker: "XYZ", name: "Block, Inc.", kr_name: "블록", market: "NYSE", sp500: true},
  {ticker: "BNY", name: "BNY Mellon", kr_name: "뱅크 오브 뉴욕 멜론", market: "NYSE", sp500: true},
  {ticker: "BA", name: "Boeing", kr_name: "보잉", market: "NYSE", sp500: true},
  {ticker: "BSX", name: "Boston Scientific", kr_name: "보스턴 사이언티픽", market: "NYSE", sp500: true},
  {ticker: "BMY", name: "Bristol Myers Squibb", kr_name: "브리스톨 마이어스 스큅", market: "NYSE", sp500: true},
  {ticker: "BR", name: "Broadridge Financial Solutions", kr_name: "브로드리지 파이낸셜 솔루션", market: "NYSE", sp500: true},
  {ticker: "BRO", name: "Brown & Brown", kr_name: "브라운 앤드 브라운", market: "NYSE", sp500: true},
  {ticker: "BF.B", name: "Brown–Forman", kr_name: "브라운 포맨 B", market: "NYSE", sp500: true},
  {ticker: "BLDR", name: "Builders FirstSource", kr_name: "빌더스 퍼스트소스", market: "NYSE", sp500: true},
  {ticker: "BG", name: "Bunge Global", kr_name: "번지 글로벌", market: "NYSE", sp500: true},
  {ticker: "BXP", name: "BXP, Inc.", kr_name: "BXP", market: "NYSE", sp500: true},
  {ticker: "CHRW", name: "C.H. Robinson", kr_name: "CH 로빈슨 월드와이드", market: "NYSE", sp500: true},
  {ticker: "CPT", name: "Camden Property Trust", kr_name: "캠던 프라퍼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "COF", name: "Capital One", kr_name: "캐피털 원 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "CAH", name: "Cardinal Health", kr_name: "카디널 헬스", market: "NYSE", sp500: true},
  {ticker: "CCL", name: "Carnival Corporation", kr_name: "카니발", market: "NYSE", sp500: true},
  {ticker: "CARR", name: "Carrier Global", kr_name: "캐리어 글로벌", market: "NYSE", sp500: true},
  {ticker: "CVNA", name: "Carvana", kr_name: "카바나", market: "NYSE", sp500: true},
  {ticker: "CASY", name: "Casey's", kr_name: "케이시스 제너럴 스토어스", market: "NYSE", sp500: true},
  {ticker: "CAT", name: "Caterpillar Inc.", kr_name: "캐터필러", market: "NYSE", sp500: true},
  {ticker: "CBOE", name: "Cboe Global Markets", kr_name: "씨보 글로벌 마켓", market: "NYSE", sp500: true},
  {ticker: "CBRE", name: "CBRE Group", kr_name: "CBRE 그룹", market: "NYSE", sp500: true},
  {ticker: "CDW", name: "CDW Corporation", kr_name: "CDW", market: "NYSE", sp500: true},
  {ticker: "COR", name: "Cencora", kr_name: "센코라", market: "NYSE", sp500: true},
  {ticker: "CNC", name: "Centene Corporation", kr_name: "센틴", market: "NYSE", sp500: true},
  {ticker: "CNP", name: "CenterPoint Energy", kr_name: "센터포인트 에너지", market: "NYSE", sp500: true},
  {ticker: "CF", name: "CF Industries", kr_name: "CF 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "CRL", name: "Charles River Laboratories", kr_name: "찰스 리버 래브러토리스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "SCHW", name: "Charles Schwab Corporation", kr_name: "찰스 슈왑", market: "NYSE", sp500: true},
  {ticker: "CHTR", name: "Charter Communications", kr_name: "차터 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "CVX", name: "Chevron Corporation", kr_name: "셰브론", market: "NYSE", sp500: true},
  {ticker: "CMG", name: "Chipotle Mexican Grill", kr_name: "치폴레 멕시칸 그릴", market: "NYSE", sp500: true},
  {ticker: "CB", name: "Chubb Limited", kr_name: "처브", market: "NYSE", sp500: true},
  {ticker: "CHD", name: "Church & Dwight", kr_name: "처치 앤드 드와이트", market: "NYSE", sp500: true},
  {ticker: "CIEN", name: "Ciena", kr_name: "시에나", market: "NYSE", sp500: true},
  {ticker: "CI", name: "Cigna", kr_name: "시그나 그룹", market: "NYSE", sp500: true},
  {ticker: "CINF", name: "Cincinnati Financial", kr_name: "신시내티 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "C", name: "Citigroup", kr_name: "씨티그룹", market: "NYSE", sp500: true},
  {ticker: "CFG", name: "Citizens Financial Group", kr_name: "시티즌스 파이낸셜 그룹", market: "NYSE", sp500: true},
  {ticker: "CLX", name: "Clorox", kr_name: "크로락스", market: "NYSE", sp500: true},
  {ticker: "CME", name: "CME Group", kr_name: "CME 그룹", market: "NYSE", sp500: true},
  {ticker: "CMS", name: "CMS Energy", kr_name: "CMS 에너지", market: "NYSE", sp500: true},
  {ticker: "KO", name: "Coca-Cola Company (The)", kr_name: "코카콜라", market: "NYSE", sp500: true},
  {ticker: "CTSH", name: "Cognizant", kr_name: "코그니전트 테크놀로지 솔루션스", market: "NYSE", sp500: true},
  {ticker: "COHR", name: "Coherent Corp.", kr_name: "코히어런트", market: "NYSE", sp500: true},
  {ticker: "COIN", name: "Coinbase", kr_name: "코인베이스 글로벌", market: "NYSE", sp500: true},
  {ticker: "CL", name: "Colgate-Palmolive", kr_name: "콜게이트 팜올리브", market: "NYSE", sp500: true},
  {ticker: "FIX", name: "Comfort Systems USA", kr_name: "컴포트 시스템스 USA", market: "NYSE", sp500: true},
  {ticker: "COP", name: "ConocoPhillips", kr_name: "코노코필립스", market: "NYSE", sp500: true},
  {ticker: "ED", name: "Consolidated Edison", kr_name: "컨솔리데이티드 에디슨", market: "NYSE", sp500: true},
  {ticker: "STZ", name: "Constellation Brands", kr_name: "컨스털레이션 브랜즈", market: "NYSE", sp500: true},
  {ticker: "COO", name: "Cooper Companies (The)", kr_name: "쿠퍼", market: "NYSE", sp500: true},
  {ticker: "GLW", name: "Corning Inc.", kr_name: "코닝", market: "NYSE", sp500: true},
  {ticker: "CPAY", name: "Corpay", kr_name: "코페이", market: "NYSE", sp500: true},
  {ticker: "CTVA", name: "Corteva", kr_name: "코르테바", market: "NYSE", sp500: true},
  {ticker: "CSGP", name: "CoStar Group", kr_name: "코스타 그룹", market: "NYSE", sp500: true},
  {ticker: "CRH", name: "CRH plc", kr_name: "CRH", market: "NYSE", sp500: true},
  {ticker: "CCI", name: "Crown Castle", kr_name: "크라운 캐슬", market: "NYSE", sp500: true},
  {ticker: "CMI", name: "Cummins", kr_name: "커민스", market: "NYSE", sp500: true},
  {ticker: "CVS", name: "CVS Health", kr_name: "CVS 헬스", market: "NYSE", sp500: true},
  {ticker: "DHR", name: "Danaher Corporation", kr_name: "다나허", market: "NYSE", sp500: true},
  {ticker: "DRI", name: "Darden Restaurants", kr_name: "다든 레스토랑", market: "NYSE", sp500: true},
  {ticker: "DVA", name: "DaVita", kr_name: "다비타", market: "NYSE", sp500: true},
  {ticker: "DECK", name: "Deckers Brands", kr_name: "덱커 아웃도어", market: "NYSE", sp500: true},
  {ticker: "DE", name: "Deere & Company", kr_name: "디어", market: "NYSE", sp500: true},
  {ticker: "DELL", name: "Dell Technologies", kr_name: "델 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "DAL", name: "Delta Air Lines", kr_name: "델타 에어라인스", market: "NYSE", sp500: true},
  {ticker: "DVN", name: "Devon Energy", kr_name: "데번 에너지", market: "NYSE", sp500: true},
  {ticker: "DLR", name: "Digital Realty", kr_name: "디지털 리얼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "DG", name: "Dollar General", kr_name: "달러 제너럴", market: "NYSE", sp500: true},
  {ticker: "DLTR", name: "Dollar Tree", kr_name: "달러 트리", market: "NYSE", sp500: true},
  {ticker: "D", name: "Dominion Energy", kr_name: "도미니언 에너지", market: "NYSE", sp500: true},
  {ticker: "DPZ", name: "Domino's", kr_name: "도미노 피자", market: "NYSE", sp500: true},
  {ticker: "DOV", name: "Dover Corporation", kr_name: "도버", market: "NYSE", sp500: true},
  {ticker: "DOW", name: "Dow Inc.", kr_name: "다우", market: "NYSE", sp500: true},
  {ticker: "DHI", name: "D. R. Horton", kr_name: "닥터 호턴", market: "NYSE", sp500: true},
  {ticker: "DTE", name: "DTE Energy", kr_name: "DTE 에너지", market: "NYSE", sp500: true},
  {ticker: "DUK", name: "Duke Energy", kr_name: "듀크 에너지", market: "NYSE", sp500: true},
  {ticker: "DD", name: "DuPont", kr_name: "듀폰", market: "NYSE", sp500: true},
  {ticker: "ETN", name: "Eaton Corporation", kr_name: "이턴 코퍼레이션", market: "NYSE", sp500: true},
  {ticker: "EBAY", name: "eBay Inc.", kr_name: "이베이", market: "NYSE", sp500: true},
  {ticker: "ECHO", name: "EchoStar", kr_name: "에코스타", market: "NYSE", sp500: true},
  {ticker: "ECL", name: "Ecolab", kr_name: "에코랩", market: "NYSE", sp500: true},
  {ticker: "EIX", name: "Edison International", kr_name: "에디슨 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "EW", name: "Edwards Lifesciences", kr_name: "에드워즈 라이프사이언시스", market: "NYSE", sp500: true},
  {ticker: "ELV", name: "Elevance Health", kr_name: "엘리밴스 헬스", market: "NYSE", sp500: true},
  {ticker: "EME", name: "Emcor", kr_name: "엠코 그룹", market: "NYSE", sp500: true},
  {ticker: "EMR", name: "Emerson Electric", kr_name: "에머슨 일렉트릭", market: "NYSE", sp500: true},
  {ticker: "ETR", name: "Entergy", kr_name: "엔터지", market: "NYSE", sp500: true},
  {ticker: "EOG", name: "EOG Resources", kr_name: "EOG 리소시스", market: "NYSE", sp500: true},
  {ticker: "EQT", name: "EQT Corporation", kr_name: "EQT", market: "NYSE", sp500: true},
  {ticker: "EFX", name: "Equifax", kr_name: "에퀴팩스", market: "NYSE", sp500: true},
  {ticker: "EQIX", name: "Equinix", kr_name: "에퀴닉스", market: "NYSE", sp500: true},
  {ticker: "EQR", name: "Equity Residential", kr_name: "에퀴티 레지덴셜", market: "NYSE", sp500: true},
  {ticker: "ERIE", name: "Erie Indemnity", kr_name: "이리 인뎀너티", market: "NYSE", sp500: true},
  {ticker: "ESS", name: "Essex Property Trust", kr_name: "에섹스 프라퍼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "EL", name: "Estée Lauder Companies (The)", kr_name: "에스티 로더", market: "NYSE", sp500: true},
  {ticker: "EG", name: "Everest Group", kr_name: "에베레스트 그룹", market: "NYSE", sp500: true},
  {ticker: "EVRG", name: "Evergy", kr_name: "에버지", market: "NYSE", sp500: true},
  {ticker: "ES", name: "Eversource Energy", kr_name: "에버소스 에너지", market: "NYSE", sp500: true},
  {ticker: "EXE", name: "Expand Energy", kr_name: "익스팬드 에너지", market: "NYSE", sp500: true},
  {ticker: "EXPE", name: "Expedia Group", kr_name: "익스피디아 그룹", market: "NYSE", sp500: true},
  {ticker: "EXPD", name: "Expeditors International", kr_name: "익스피다이터스 인터내셔널 오브 워싱턴", market: "NYSE", sp500: true},
  {ticker: "EXR", name: "Extra Space Storage", kr_name: "엑스트라 스페이스 스토리지", market: "NYSE", sp500: true},
  {ticker: "XOM", name: "ExxonMobil", kr_name: "엑슨 모빌", market: "NYSE", sp500: true},
  {ticker: "FFIV", name: "F5, Inc.", kr_name: "F5", market: "NYSE", sp500: true},
  {ticker: "FDS", name: "FactSet", kr_name: "팩트셋 리서치 시스템스", market: "NYSE", sp500: true},
  {ticker: "FICO", name: "Fair Isaac", kr_name: "페어 아이작", market: "NYSE", sp500: true},
  {ticker: "FRT", name: "Federal Realty Investment Trust", kr_name: "페더럴 리얼티 인베스트먼트", market: "NYSE", sp500: true},
  {ticker: "FDX", name: "FedEx", kr_name: "페덱스", market: "NYSE", sp500: true},
  {ticker: "FDXF", name: "FedEx Freight", kr_name: "FedEx Freight Holding Company Inc", market: "NYSE", sp500: true},
  {ticker: "FIS", name: "Fidelity National Information Services", kr_name: "피델리티 내셔널 인포메이션 서비시스", market: "NYSE", sp500: true},
  {ticker: "FITB", name: "Fifth Third Bancorp", kr_name: "피프스 서드 뱅코프", market: "NYSE", sp500: true},
  {ticker: "FSLR", name: "First Solar", kr_name: "퍼스트 솔라", market: "NYSE", sp500: true},
  {ticker: "FE", name: "FirstEnergy", kr_name: "퍼스트에너지", market: "NYSE", sp500: true},
  {ticker: "FISV", name: "Fiserv", kr_name: "파이서브", market: "NYSE", sp500: true},
  {ticker: "FLEX", name: "Flex Ltd.", kr_name: "플렉스", market: "NYSE", sp500: true},
  {ticker: "F", name: "Ford Motor Company", kr_name: "포드 모터", market: "NYSE", sp500: true},
  {ticker: "FTV", name: "Fortive", kr_name: "포티브", market: "NYSE", sp500: true},
  {ticker: "FOXA", name: "Fox Corporation (Class A)", kr_name: "폭스 A", market: "NYSE", sp500: true},
  {ticker: "FOX", name: "Fox Corporation (Class B)", kr_name: "폭스 B", market: "NYSE", sp500: true},
  {ticker: "BEN", name: "Franklin Resources", kr_name: "프랭클린 리소시스", market: "NYSE", sp500: true},
  {ticker: "FCX", name: "Freeport-McMoRan", kr_name: "프리포트 맥모란", market: "NYSE", sp500: true},
  {ticker: "GRMN", name: "Garmin", kr_name: "가민", market: "NYSE", sp500: true},
  {ticker: "IT", name: "Gartner", kr_name: "가트너", market: "NYSE", sp500: true},
  {ticker: "GE", name: "GE Aerospace", kr_name: "GE에어로스페이스", market: "NYSE", sp500: true},
  {ticker: "GEV", name: "GE Vernova", kr_name: "GE베르노바", market: "NYSE", sp500: true},
  {ticker: "GEN", name: "Gen Digital", kr_name: "젠 디지털", market: "NYSE", sp500: true},
  {ticker: "GNRC", name: "Generac", kr_name: "제네락", market: "NYSE", sp500: true},
  {ticker: "GD", name: "General Dynamics", kr_name: "제너럴 다이내믹스", market: "NYSE", sp500: true},
  {ticker: "GIS", name: "General Mills", kr_name: "제너럴 밀스", market: "NYSE", sp500: true},
  {ticker: "GM", name: "General Motors", kr_name: "제너럴 모터스", market: "NYSE", sp500: true},
  {ticker: "GPC", name: "Genuine Parts Company", kr_name: "제뉴인 파츠", market: "NYSE", sp500: true},
  {ticker: "GPN", name: "Global Payments", kr_name: "글로벌 페이먼츠", market: "NYSE", sp500: true},
  {ticker: "GL", name: "Globe Life", kr_name: "글로브 라이프", market: "NYSE", sp500: true},
  {ticker: "GDDY", name: "GoDaddy", kr_name: "고대디", market: "NYSE", sp500: true},
  {ticker: "GS", name: "Goldman Sachs", kr_name: "골드만삭스", market: "NYSE", sp500: true},
  {ticker: "HAL", name: "Halliburton", kr_name: "할리버턴", market: "NYSE", sp500: true},
  {ticker: "HIG", name: "Hartford (The)", kr_name: "하트포드 인슈어런스 그룹", market: "NYSE", sp500: true},
  {ticker: "HAS", name: "Hasbro", kr_name: "해즈브로", market: "NYSE", sp500: true},
  {ticker: "HCA", name: "HCA Healthcare", kr_name: "HCA 헬스케어", market: "NYSE", sp500: true},
  {ticker: "DOC", name: "Healthpeak Properties", kr_name: "헬스피크 프라퍼티스", market: "NYSE", sp500: true},
  {ticker: "HSIC", name: "Henry Schein", kr_name: "헨리 셰인", market: "NYSE", sp500: true},
  {ticker: "HSY", name: "Hershey Company (The)", kr_name: "허쉬", market: "NYSE", sp500: true},
  {ticker: "HPE", name: "Hewlett Packard Enterprise", kr_name: "휴렛 팩커드 엔터프라이즈", market: "NYSE", sp500: true},
  {ticker: "HLT", name: "Hilton Worldwide", kr_name: "힐튼 월드와이드", market: "NYSE", sp500: true},
  {ticker: "HD", name: "Home Depot (The)", kr_name: "홈 디포", market: "NYSE", sp500: true},
  {ticker: "HRL", name: "Hormel Foods", kr_name: "호멜 푸즈", market: "NYSE", sp500: true},
  {ticker: "HST", name: "Host Hotels & Resorts", kr_name: "호스트 호텔스 앤드 리조츠", market: "NYSE", sp500: true},
  {ticker: "HWM", name: "Howmet Aerospace", kr_name: "하우멧 에어로스페이스", market: "NYSE", sp500: true},
  {ticker: "HPQ", name: "HP Inc.", kr_name: "HP", market: "NYSE", sp500: true},
  {ticker: "HUBB", name: "Hubbell Incorporated", kr_name: "허벨", market: "NYSE", sp500: true},
  {ticker: "HUM", name: "Humana", kr_name: "휴마나", market: "NYSE", sp500: true},
  {ticker: "HBAN", name: "Huntington Bancshares", kr_name: "헌팅턴 뱅크셰어스", market: "NYSE", sp500: true},
  {ticker: "HII", name: "Huntington Ingalls Industries", kr_name: "헌팅턴 잉걸스 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "IBM", name: "IBM", kr_name: "IBM", market: "NYSE", sp500: true},
  {ticker: "IEX", name: "IDEX Corporation", kr_name: "아이덱스", market: "NYSE", sp500: true},
  {ticker: "ITW", name: "Illinois Tool Works", kr_name: "일리노이 툴 웍스", market: "NYSE", sp500: true},
  {ticker: "INCY", name: "Incyte", kr_name: "인사이트", market: "NYSE", sp500: true},
  {ticker: "IR", name: "Ingersoll Rand", kr_name: "잉가솔랜드", market: "NYSE", sp500: true},
  {ticker: "PODD", name: "Insulet Corporation", kr_name: "인슐릿", market: "NYSE", sp500: true},
  {ticker: "IBKR", name: "Interactive Brokers", kr_name: "인터랙티브 브로커스 그룹", market: "NYSE", sp500: true},
  {ticker: "ICE", name: "Intercontinental Exchange", kr_name: "인터컨티넨털 익스체인지", market: "NYSE", sp500: true},
  {ticker: "IFF", name: "International Flavors & Fragrances", kr_name: "인터내셔널 플레이버스 앤드 프레그런스", market: "NYSE", sp500: true},
  {ticker: "IP", name: "International Paper", kr_name: "인터내셔널 페이퍼", market: "NYSE", sp500: true},
  {ticker: "IVZ", name: "Invesco", kr_name: "인베스코", market: "NYSE", sp500: true},
  {ticker: "INVH", name: "Invitation Homes", kr_name: "인비테이션 홈스", market: "NYSE", sp500: true},
  {ticker: "IQV", name: "IQVIA", kr_name: "아이큐비아", market: "NYSE", sp500: true},
  {ticker: "IRM", name: "Iron Mountain", kr_name: "아이언 마운틴", market: "NYSE", sp500: true},
  {ticker: "JBHT", name: "J.B. Hunt", kr_name: "JB 헌트 트랜스포트 서비시스", market: "NYSE", sp500: true},
  {ticker: "JBL", name: "Jabil", kr_name: "자빌", market: "NYSE", sp500: true},
  {ticker: "JKHY", name: "Jack Henry & Associates", kr_name: "헨리 잭 앤드 어소시에이츠", market: "NYSE", sp500: true},
  {ticker: "J", name: "Jacobs Solutions", kr_name: "제이콥스 솔루션스", market: "NYSE", sp500: true},
  {ticker: "JNJ", name: "Johnson & Johnson", kr_name: "존슨 앤드 존슨", market: "NYSE", sp500: true},
  {ticker: "JCI", name: "Johnson Controls", kr_name: "존슨 콘트롤즈 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "JPM", name: "JPMorgan Chase", kr_name: "제이피모간 체이스", market: "NYSE", sp500: true},
  {ticker: "KVUE", name: "Kenvue", kr_name: "켄뷰", market: "NYSE", sp500: true},
  {ticker: "KEY", name: "KeyCorp", kr_name: "키코프", market: "NYSE", sp500: true},
  {ticker: "KEYS", name: "Keysight Technologies", kr_name: "키사이트 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "KMB", name: "Kimberly-Clark", kr_name: "킴벌리클라크", market: "NYSE", sp500: true},
  {ticker: "KIM", name: "Kimco Realty", kr_name: "킴코 리얼티", market: "NYSE", sp500: true},
  {ticker: "KMI", name: "Kinder Morgan", kr_name: "킨더 모건", market: "NYSE", sp500: true},
  {ticker: "KKR", name: "KKR & Co.", kr_name: "KKR & CO", market: "NYSE", sp500: true},
  {ticker: "KR", name: "Kroger", kr_name: "크로거", market: "NYSE", sp500: true},
  {ticker: "LHX", name: "L3Harris", kr_name: "L3 해리스 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "LH", name: "Labcorp", kr_name: "랩코프", market: "NYSE", sp500: true},
  {ticker: "LVS", name: "Las Vegas Sands", kr_name: "라스베이거스 샌즈", market: "NYSE", sp500: true},
  {ticker: "LDOS", name: "Leidos", kr_name: "레이도스", market: "NYSE", sp500: true},
  {ticker: "LEN", name: "Lennar", kr_name: "레나", market: "NYSE", sp500: true},
  {ticker: "LII", name: "Lennox International", kr_name: "레녹스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "LLY", name: "Lilly (Eli)", kr_name: "일라이 릴리", market: "NYSE", sp500: true},
  {ticker: "LYV", name: "Live Nation Entertainment", kr_name: "라이브 네이션 엔터테인먼트", market: "NYSE", sp500: true},
  {ticker: "LMT", name: "Lockheed Martin", kr_name: "록히드 마틴", market: "NYSE", sp500: true},
  {ticker: "L", name: "Loews Corporation", kr_name: "로우스", market: "NYSE", sp500: true},
  {ticker: "LOW", name: "Lowe's", kr_name: "로스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "LULU", name: "Lululemon Athletica", kr_name: "룰루레몬 애슬레티카", market: "NYSE", sp500: true},
  {ticker: "LYB", name: "LyondellBasell", kr_name: "라이온델바젤 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "MTB", name: "M&T Bank", kr_name: "M&T 뱅크", market: "NYSE", sp500: true},
  {ticker: "MPC", name: "Marathon Petroleum", kr_name: "매러선 페트롤리엄", market: "NYSE", sp500: true},
  {ticker: "MRSH", name: "Marsh McLennan", kr_name: "마시 앤드 매클래넌 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "MLM", name: "Martin Marietta Materials", kr_name: "마틴 마리에타 머티리얼스", market: "NYSE", sp500: true},
  {ticker: "MAS", name: "Masco", kr_name: "매스코", market: "NYSE", sp500: true},
  {ticker: "MA", name: "Mastercard", kr_name: "마스타카드", market: "NYSE", sp500: true},
  {ticker: "MKC", name: "McCormick & Company", kr_name: "매코믹 앤드 컴퍼니", market: "NYSE", sp500: true},
  {ticker: "MCD", name: "McDonald's", kr_name: "맥도날드", market: "NYSE", sp500: true},
  {ticker: "MCK", name: "McKesson Corporation", kr_name: "매케손", market: "NYSE", sp500: true},
  {ticker: "MDT", name: "Medtronic", kr_name: "메드트로닉", market: "NYSE", sp500: true},
  {ticker: "MRK", name: "Merck & Co.", kr_name: "머크", market: "NYSE", sp500: true},
  {ticker: "MET", name: "MetLife", kr_name: "메트라이프", market: "NYSE", sp500: true},
  {ticker: "MTD", name: "Mettler Toledo", kr_name: "메틀러 톨레도 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "MGM", name: "MGM Resorts", kr_name: "MGM 리조츠 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "MAA", name: "Mid-America Apartment Communities", kr_name: "미드아메리카 어파트먼트 커뮤니티스", market: "NYSE", sp500: true},
  {ticker: "MRNA", name: "Moderna", kr_name: "모더나", market: "NYSE", sp500: true},
  {ticker: "TAP", name: "Molson Coors Beverage Company", kr_name: "몰슨 쿠어스 베버리지", market: "NYSE", sp500: true},
  {ticker: "MCO", name: "Moody's Corporation", kr_name: "무디스", market: "NYSE", sp500: true},
  {ticker: "MS", name: "Morgan Stanley", kr_name: "모간스탠리", market: "NYSE", sp500: true},
  {ticker: "MOS", name: "Mosaic Company (The)", kr_name: "모자이크", market: "NYSE", sp500: true},
  {ticker: "MSI", name: "Motorola Solutions", kr_name: "모토로라 솔루션스", market: "NYSE", sp500: true},
  {ticker: "MSCI", name: "MSCI Inc.", kr_name: "MSCI", market: "NYSE", sp500: true},
  {ticker: "NDAQ", name: "Nasdaq, Inc.", kr_name: "나스닥", market: "NYSE", sp500: true},
  {ticker: "NTAP", name: "NetApp", kr_name: "넷앱", market: "NYSE", sp500: true},
  {ticker: "NEM", name: "Newmont", kr_name: "뉴몬트", market: "NYSE", sp500: true},
  {ticker: "NWSA", name: "News Corp (Class A)", kr_name: "뉴스 코퍼레이션 A", market: "NYSE", sp500: true},
  {ticker: "NWS", name: "News Corp (Class B)", kr_name: "뉴스 코퍼레이션 B", market: "NYSE", sp500: true},
  {ticker: "NEE", name: "NextEra Energy", kr_name: "넥스트에라 에너지", market: "NYSE", sp500: true},
  {ticker: "NKE", name: "Nike, Inc.", kr_name: "나이키 B", market: "NYSE", sp500: true},
  {ticker: "NI", name: "NiSource", kr_name: "나이소스", market: "NYSE", sp500: true},
  {ticker: "NDSN", name: "Nordson Corporation", kr_name: "노드슨", market: "NYSE", sp500: true},
  {ticker: "NSC", name: "Norfolk Southern", kr_name: "노퍽서던", market: "NYSE", sp500: true},
  {ticker: "NTRS", name: "Northern Trust", kr_name: "노던 트러스트", market: "NYSE", sp500: true},
  {ticker: "NOC", name: "Northrop Grumman", kr_name: "노스롭 그루만", market: "NYSE", sp500: true},
  {ticker: "NCLH", name: "Norwegian Cruise Line Holdings", kr_name: "노르웨이지언 크루즈 라인", market: "NYSE", sp500: true},
  {ticker: "NRG", name: "NRG Energy", kr_name: "NRG 에너지", market: "NYSE", sp500: true},
  {ticker: "NUE", name: "Nucor", kr_name: "뉴코", market: "NYSE", sp500: true},
  {ticker: "NVR", name: "NVR, Inc.", kr_name: "NVR", market: "NYSE", sp500: true},
  {ticker: "OXY", name: "Occidental Petroleum", kr_name: "옥시덴털 페트롤리엄", market: "NYSE", sp500: true},
  {ticker: "OMC", name: "Omnicom Group", kr_name: "옴니콤 그룹", market: "NYSE", sp500: true},
  {ticker: "ON", name: "ON Semiconductor", kr_name: "온 세미컨덕터", market: "NYSE", sp500: true},
  {ticker: "OKE", name: "Oneok", kr_name: "원오크", market: "NYSE", sp500: true},
  {ticker: "ORCL", name: "Oracle Corporation", kr_name: "오라클", market: "NYSE", sp500: true},
  {ticker: "OTIS", name: "Otis Worldwide", kr_name: "오티스 월드와이드", market: "NYSE", sp500: true},
  {ticker: "PKG", name: "Packaging Corporation of America", kr_name: "패키징 코퍼레이션 오브 아메리카", market: "NYSE", sp500: true},
  {ticker: "PSKY", name: "Paramount Skydance Corporation", kr_name: "파라마운트 스카이댄스", market: "NYSE", sp500: true},
  {ticker: "PH", name: "Parker Hannifin", kr_name: "파카 하니핀", market: "NYSE", sp500: true},
  {ticker: "PNR", name: "Pentair", kr_name: "펜테어", market: "NYSE", sp500: true},
  {ticker: "PFE", name: "Pfizer", kr_name: "화이자", market: "NYSE", sp500: true},
  {ticker: "PCG", name: "PG&E Corporation", kr_name: "퍼시픽 가스 앤드 일렉트릭", market: "NYSE", sp500: true},
  {ticker: "PM", name: "Philip Morris International", kr_name: "필립 모리스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "PSX", name: "Phillips 66", kr_name: "필립스 66", market: "NYSE", sp500: true},
  {ticker: "PNW", name: "Pinnacle West Capital", kr_name: "피너클 웨스트 캐피털", market: "NYSE", sp500: true},
  {ticker: "PNC", name: "PNC Financial Services", kr_name: "PNC 파이낸셜 서비시스", market: "NYSE", sp500: true},
  {ticker: "PPG", name: "PPG Industries", kr_name: "PPG 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "PPL", name: "PPL Corporation", kr_name: "PPL", market: "NYSE", sp500: true},
  {ticker: "PFG", name: "Principal Financial Group", kr_name: "프린서플 파이낸셜 그룹", market: "NYSE", sp500: true},
  {ticker: "PG", name: "Procter & Gamble", kr_name: "프록터 앤드 갬블", market: "NYSE", sp500: true},
  {ticker: "PGR", name: "Progressive Corporation", kr_name: "프로그레시브", market: "NYSE", sp500: true},
  {ticker: "PLD", name: "Prologis", kr_name: "프로로지스", market: "NYSE", sp500: true},
  {ticker: "PRU", name: "Prudential Financial", kr_name: "푸르덴셜 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "PEG", name: "Public Service Enterprise Group", kr_name: "퍼블릭 서비스 엔터프라이즈", market: "NYSE", sp500: true},
  {ticker: "PTC", name: "PTC Inc.", kr_name: "PTC", market: "NYSE", sp500: true},
  {ticker: "PSA", name: "Public Storage", kr_name: "퍼블릭 스토리지", market: "NYSE", sp500: true},
  {ticker: "PHM", name: "PulteGroup", kr_name: "풀티 그룹", market: "NYSE", sp500: true},
  {ticker: "PWR", name: "Quanta Services", kr_name: "콴타 서비시스", market: "NYSE", sp500: true},
  {ticker: "DGX", name: "Quest Diagnostics", kr_name: "퀘스트 다이어그노스틱스", market: "NYSE", sp500: true},
  {ticker: "Q", name: "Qnity Electronics", kr_name: "QNITY ELECTRONICS INC.", market: "NYSE", sp500: true},
  {ticker: "RL", name: "Ralph Lauren Corporation", kr_name: "랄프 로렌", market: "NYSE", sp500: true},
  {ticker: "RJF", name: "Raymond James Financial", kr_name: "레이먼드 제임스 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "RTX", name: "RTX Corporation", kr_name: "RTX", market: "NYSE", sp500: true},
  {ticker: "O", name: "Realty Income", kr_name: "리얼티 인컴", market: "NYSE", sp500: true},
  {ticker: "REG", name: "Regency Centers", kr_name: "리젠시 센터스", market: "NYSE", sp500: true},
  {ticker: "RF", name: "Regions Financial Corporation", kr_name: "리전스 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "RSG", name: "Republic Services", kr_name: "리퍼블릭 서비시스", market: "NYSE", sp500: true},
  {ticker: "RMD", name: "ResMed", kr_name: "레즈메드", market: "NYSE", sp500: true},
  {ticker: "RVTY", name: "Revvity", kr_name: "레비티", market: "NYSE", sp500: true},
  {ticker: "HOOD", name: "Robinhood Markets", kr_name: "로빈훗 마케츠", market: "NYSE", sp500: true},
  {ticker: "ROK", name: "Rockwell Automation", kr_name: "로크웰 오토메이션", market: "NYSE", sp500: true},
  {ticker: "ROL", name: "Rollins, Inc.", kr_name: "롤린스", market: "NYSE", sp500: true},
  {ticker: "RCL", name: "Royal Caribbean Group", kr_name: "로열 캐리비언 크루즈", market: "NYSE", sp500: true},
  {ticker: "SPGI", name: "S&P Global", kr_name: "S&P 글로벌", market: "NYSE", sp500: true},
  {ticker: "CRM", name: "Salesforce", kr_name: "세일스포스", market: "NYSE", sp500: true},
  {ticker: "SBAC", name: "SBA Communications", kr_name: "SBA 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "SLB", name: "Schlumberger", kr_name: "슐럼버거", market: "NYSE", sp500: true},
  {ticker: "SRE", name: "Sempra", kr_name: "셈프라", market: "NYSE", sp500: true},
  {ticker: "NOW", name: "ServiceNow", kr_name: "서비스나우", market: "NYSE", sp500: true},
  {ticker: "SHW", name: "Sherwin-Williams", kr_name: "셔윈 윌리엄스", market: "NYSE", sp500: true},
  {ticker: "SPG", name: "Simon Property Group", kr_name: "사이먼 프라퍼티 그룹", market: "NYSE", sp500: true},
  {ticker: "SWKS", name: "Skyworks Solutions", kr_name: "스카이웍스 솔루션스", market: "NYSE", sp500: true},
  {ticker: "SJM", name: "J.M. Smucker Company (The)", kr_name: "스머커", market: "NYSE", sp500: true},
  {ticker: "SW", name: "Smurfit Westrock", kr_name: "스머핏 웨스트록", market: "NYSE", sp500: true},
  {ticker: "SNA", name: "Snap-on", kr_name: "스냅 온", market: "NYSE", sp500: true},
  {ticker: "SOLV", name: "Solventum", kr_name: "솔벤텀", market: "NYSE", sp500: true},
  {ticker: "SO", name: "Southern Company", kr_name: "서던", market: "NYSE", sp500: true},
  {ticker: "LUV", name: "Southwest Airlines", kr_name: "사우스웨스트 에어라인스", market: "NYSE", sp500: true},
  {ticker: "SWK", name: "Stanley Black & Decker", kr_name: "스탠리 블랙 앤 데커", market: "NYSE", sp500: true},
  {ticker: "STT", name: "State Street Corporation", kr_name: "스테이트 스트리트", market: "NYSE", sp500: true},
  {ticker: "STLD", name: "Steel Dynamics", kr_name: "스틸 다이내믹스", market: "NYSE", sp500: true},
  {ticker: "STE", name: "Steris", kr_name: "스테리스", market: "NYSE", sp500: true},
  {ticker: "SYK", name: "Stryker Corporation", kr_name: "스트라이커", market: "NYSE", sp500: true},
  {ticker: "SMCI", name: "Supermicro", kr_name: "슈퍼 마이크로 컴퓨터", market: "NYSE", sp500: true},
  {ticker: "SYF", name: "Synchrony Financial", kr_name: "싱크로니 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "SYY", name: "Sysco", kr_name: "시스코", market: "NYSE", sp500: true},
  {ticker: "TROW", name: "T. Rowe Price", kr_name: "티 로 프라이스 그룹", market: "NYSE", sp500: true},
  {ticker: "TPR", name: "Tapestry, Inc.", kr_name: "태피스트리", market: "NYSE", sp500: true},
  {ticker: "TRGP", name: "Targa Resources", kr_name: "타르가 리소시스", market: "NYSE", sp500: true},
  {ticker: "TGT", name: "Target Corporation", kr_name: "타겟", market: "NYSE", sp500: true},
  {ticker: "TEL", name: "TE Connectivity", kr_name: "TE 커넥티비티", market: "NYSE", sp500: true},
  {ticker: "TDY", name: "Teledyne Technologies", kr_name: "텔레다인 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "TPL", name: "Texas Pacific Land Corporation", kr_name: "텍사스 퍼시픽 랜드", market: "NYSE", sp500: true},
  {ticker: "TXT", name: "Textron", kr_name: "텍스트론", market: "NYSE", sp500: true},
  {ticker: "TMO", name: "Thermo Fisher Scientific", kr_name: "써모 피셔 사이언티픽", market: "NYSE", sp500: true},
  {ticker: "TJX", name: "TJX Companies", kr_name: "TJX", market: "NYSE", sp500: true},
  {ticker: "TKO", name: "TKO Group Holdings", kr_name: "TKO 그룹", market: "NYSE", sp500: true},
  {ticker: "TTD", name: "Trade Desk (The)", kr_name: "트레이드 데스크", market: "NYSE", sp500: true},
  {ticker: "TSCO", name: "Tractor Supply", kr_name: "트랙터 서플라이", market: "NYSE", sp500: true},
  {ticker: "TT", name: "Trane Technologies", kr_name: "트레인 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "TDG", name: "TransDigm Group", kr_name: "트랜스다임 그룹", market: "NYSE", sp500: true},
  {ticker: "TRV", name: "Travelers Companies (The)", kr_name: "트래블러스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "TRMB", name: "Trimble Inc.", kr_name: "트림블", market: "NYSE", sp500: true},
  {ticker: "TFC", name: "Truist Financial", kr_name: "트루이스트 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "TYL", name: "Tyler Technologies", kr_name: "타일러 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "TSN", name: "Tyson Foods", kr_name: "타이슨 푸드", market: "NYSE", sp500: true},
  {ticker: "USB", name: "U.S. Bancorp", kr_name: "US 뱅코프", market: "NYSE", sp500: true},
  {ticker: "UBER", name: "Uber", kr_name: "우버 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "UDR", name: "UDR, Inc.", kr_name: "UDR", market: "NYSE", sp500: true},
  {ticker: "ULTA", name: "Ulta Beauty", kr_name: "울타 뷰티", market: "NYSE", sp500: true},
  {ticker: "UNP", name: "Union Pacific Corporation", kr_name: "유니언 퍼시픽", market: "NYSE", sp500: true},
  {ticker: "UAL", name: "United Airlines Holdings", kr_name: "유나이티드 에어라인스", market: "NYSE", sp500: true},
  {ticker: "UPS", name: "United Parcel Service", kr_name: "UPS", market: "NYSE", sp500: true},
  {ticker: "URI", name: "United Rentals", kr_name: "유나이티드 렌탈스", market: "NYSE", sp500: true},
  {ticker: "UNH", name: "UnitedHealth Group", kr_name: "유나이티드헬스 그룹", market: "NYSE", sp500: true},
  {ticker: "UHS", name: "Universal Health Services", kr_name: "유니버설 헬스 서비시스", market: "NYSE", sp500: true},
  {ticker: "VLO", name: "Valero Energy", kr_name: "발레로 에너지", market: "NYSE", sp500: true},
  {ticker: "VEEV", name: "Veeva Systems", kr_name: "비바 시스템스", market: "NYSE", sp500: true},
  {ticker: "VTR", name: "Ventas", kr_name: "벤타스", market: "NYSE", sp500: true},
  {ticker: "VLTO", name: "Veralto", kr_name: "버럴토", market: "NYSE", sp500: true},
  {ticker: "VRSN", name: "Verisign", kr_name: "베리사인", market: "NYSE", sp500: true},
  {ticker: "VRSK", name: "Verisk Analytics", kr_name: "베리스크 애널리틱스", market: "NYSE", sp500: true},
  {ticker: "VZ", name: "Verizon", kr_name: "버라이존 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "VRT", name: "Vertiv", kr_name: "버티브", market: "NYSE", sp500: true},
  {ticker: "VTRS", name: "Viatris", kr_name: "비아트리스", market: "NYSE", sp500: true},
  {ticker: "VICI", name: "Vici Properties", kr_name: "비치 프라퍼티스", market: "NYSE", sp500: true},
  {ticker: "V", name: "Visa Inc.", kr_name: "비자", market: "NYSE", sp500: true},
  {ticker: "VST", name: "Vistra Corp.", kr_name: "비스트라 에너지", market: "NYSE", sp500: true},
  {ticker: "VMC", name: "Vulcan Materials Company", kr_name: "벌칸 머티리얼스", market: "NYSE", sp500: true},
  {ticker: "WRB", name: "W. R. Berkley Corporation", kr_name: "WR 버클리", market: "NYSE", sp500: true},
  {ticker: "GWW", name: "W. W. Grainger", kr_name: "WW 그레인저", market: "NYSE", sp500: true},
  {ticker: "WAB", name: "Wabtec", kr_name: "왑텍", market: "NYSE", sp500: true},
  {ticker: "DIS", name: "Walt Disney Company (The)", kr_name: "월트 디즈니", market: "NYSE", sp500: true},
  {ticker: "WM", name: "Waste Management", kr_name: "웨이스트 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "WAT", name: "Waters Corporation", kr_name: "워터스", market: "NYSE", sp500: true},
  {ticker: "WEC", name: "WEC Energy Group", kr_name: "WEC 에너지 그룹", market: "NYSE", sp500: true},
  {ticker: "WFC", name: "Wells Fargo", kr_name: "웰스파고", market: "NYSE", sp500: true},
  {ticker: "WELL", name: "Welltower", kr_name: "웰타워", market: "NYSE", sp500: true},
  {ticker: "WST", name: "West Pharmaceutical Services", kr_name: "웨스트 파마슈티컬 서비시즈", market: "NYSE", sp500: true},
  {ticker: "WY", name: "Weyerhaeuser", kr_name: "와이어하우저", market: "NYSE", sp500: true},
  {ticker: "WSM", name: "Williams-Sonoma, Inc.", kr_name: "윌리엄스 소노마", market: "NYSE", sp500: true},
  {ticker: "WMB", name: "Williams Companies", kr_name: "윌리엄스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "WTW", name: "Willis Towers Watson", kr_name: "윌리스 타워스 왓슨", market: "NYSE", sp500: true},
  {ticker: "WYNN", name: "Wynn Resorts", kr_name: "윈 리조츠", market: "NYSE", sp500: true},
  {ticker: "XYL", name: "Xylem Inc.", kr_name: "자일럼", market: "NYSE", sp500: true},
  {ticker: "YUM", name: "Yum! Brands", kr_name: "염 브랜즈", market: "NYSE", sp500: true},
  {ticker: "ZBRA", name: "Zebra Technologies", kr_name: "지브라 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "ZBH", name: "Zimmer Biomet", kr_name: "짐머 바이오멧", market: "NYSE", sp500: true},
  {ticker: "ZTS", name: "Zoetis", kr_name: "조에티스", market: "NYSE", sp500: true}
] AS row
MATCH (old:Company {ticker: row.ticker})
WHERE old.name <> row.kr_name
SET old.name = row.kr_name;

// [2] name 키 MERGE — 삼중항이 만든 {name: kr_name, ticker: null} 노드를 흡수해 간선을
//     보존한다. 없으면 새로 만든다. 두 번째 기동부터는 같은 값을 다시 SET 하는 no-op
UNWIND [
  {ticker: "MMM", name: "3M", kr_name: "3M", market: "NYSE", sp500: true},
  {ticker: "AOS", name: "A. O. Smith", kr_name: "A O 스미스", market: "NYSE", sp500: true},
  {ticker: "ABT", name: "Abbott Laboratories", kr_name: "애보트 래브러토리스", market: "NYSE", sp500: true},
  {ticker: "ABBV", name: "AbbVie", kr_name: "애브비", market: "NYSE", sp500: true},
  {ticker: "ACN", name: "Accenture", kr_name: "액센추어", market: "NYSE", sp500: true},
  {ticker: "AES", name: "AES Corporation", kr_name: "AES", market: "NYSE", sp500: true},
  {ticker: "AFL", name: "Aflac", kr_name: "애플랙", market: "NYSE", sp500: true},
  {ticker: "A", name: "Agilent Technologies", kr_name: "애질런트 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "APD", name: "Air Products", kr_name: "에어 프라덕츠 앤드 케미컬스", market: "NYSE", sp500: true},
  {ticker: "AKAM", name: "Akamai Technologies", kr_name: "아카마이 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "ALB", name: "Albemarle Corporation", kr_name: "알버말", market: "NYSE", sp500: true},
  {ticker: "ARE", name: "Alexandria Real Estate Equities", kr_name: "알렉산드리아 리얼 에스테이트 에퀴티스", market: "NYSE", sp500: true},
  {ticker: "ALGN", name: "Align Technology", kr_name: "얼라인 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "ALLE", name: "Allegion", kr_name: "얼리지언", market: "NYSE", sp500: true},
  {ticker: "LNT", name: "Alliant Energy", kr_name: "얼라이언트 에너지", market: "NYSE", sp500: true},
  {ticker: "ALL", name: "Allstate", kr_name: "올스테이트", market: "NYSE", sp500: true},
  {ticker: "MO", name: "Altria", kr_name: "알트리아 그룹", market: "NYSE", sp500: true},
  {ticker: "AMCR", name: "Amcor", kr_name: "앰코", market: "NYSE", sp500: true},
  {ticker: "AEE", name: "Ameren", kr_name: "애머런", market: "NYSE", sp500: true},
  {ticker: "AXP", name: "American Express", kr_name: "아메리칸 엑스프레스", market: "NYSE", sp500: true},
  {ticker: "AIG", name: "American International Group", kr_name: "아메리칸 인터내셔널 그룹", market: "NYSE", sp500: true},
  {ticker: "AMT", name: "American Tower", kr_name: "아메리칸 타워", market: "NYSE", sp500: true},
  {ticker: "AWK", name: "American Water Works", kr_name: "아메리칸 워터 웍스", market: "NYSE", sp500: true},
  {ticker: "AMP", name: "Ameriprise Financial", kr_name: "어메리프라이즈 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "AME", name: "Ametek", kr_name: "아메텍", market: "NYSE", sp500: true},
  {ticker: "APH", name: "Amphenol", kr_name: "암페놀", market: "NYSE", sp500: true},
  {ticker: "AON", name: "Aon plc", kr_name: "에이온", market: "NYSE", sp500: true},
  {ticker: "APA", name: "APA Corporation", kr_name: "APA", market: "NYSE", sp500: true},
  {ticker: "APO", name: "Apollo Global Management", kr_name: "아폴로 글로벌 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "APTV", name: "Aptiv", kr_name: "앱티브", market: "NYSE", sp500: true},
  {ticker: "ACGL", name: "Arch Capital Group", kr_name: "아치 캐피털 그룹", market: "NYSE", sp500: true},
  {ticker: "ADM", name: "Archer Daniels Midland", kr_name: "아처 대니얼스 미들랜드", market: "NYSE", sp500: true},
  {ticker: "ARES", name: "Ares Management", kr_name: "아레스 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "ANET", name: "Arista Networks", kr_name: "아리스타 네트웍스", market: "NYSE", sp500: true},
  {ticker: "AJG", name: "Arthur J. Gallagher & Co.", kr_name: "아서 갤러거 앤드 컴퍼니", market: "NYSE", sp500: true},
  {ticker: "AIZ", name: "Assurant", kr_name: "어슈런트", market: "NYSE", sp500: true},
  {ticker: "T", name: "AT&T", kr_name: "AT&T", market: "NYSE", sp500: true},
  {ticker: "ATO", name: "Atmos Energy", kr_name: "애트모스 에너지", market: "NYSE", sp500: true},
  {ticker: "AZO", name: "AutoZone", kr_name: "오토존", market: "NYSE", sp500: true},
  {ticker: "AVB", name: "AvalonBay Communities", kr_name: "아발론베이 커뮤니티스", market: "NYSE", sp500: true},
  {ticker: "AVY", name: "Avery Dennison", kr_name: "에이버리 데니슨", market: "NYSE", sp500: true},
  {ticker: "BALL", name: "Ball Corporation", kr_name: "볼", market: "NYSE", sp500: true},
  {ticker: "BAC", name: "Bank of America", kr_name: "뱅크오브아메리카", market: "NYSE", sp500: true},
  {ticker: "BAX", name: "Baxter International", kr_name: "박스터 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "BDX", name: "Becton Dickinson", kr_name: "벡턴 디킨슨", market: "NYSE", sp500: true},
  {ticker: "BRK.B", name: "Berkshire Hathaway", kr_name: "버크셔 해서웨이 B", market: "NYSE", sp500: true},
  {ticker: "BBY", name: "Best Buy", kr_name: "베스트 바이", market: "NYSE", sp500: true},
  {ticker: "TECH", name: "Bio-Techne", kr_name: "바이오 테크네", market: "NYSE", sp500: true},
  {ticker: "BIIB", name: "Biogen", kr_name: "바이오젠", market: "NYSE", sp500: true},
  {ticker: "BLK", name: "BlackRock", kr_name: "블랙록", market: "NYSE", sp500: true},
  {ticker: "BX", name: "Blackstone Inc.", kr_name: "블랙스톤", market: "NYSE", sp500: true},
  {ticker: "XYZ", name: "Block, Inc.", kr_name: "블록", market: "NYSE", sp500: true},
  {ticker: "BNY", name: "BNY Mellon", kr_name: "뱅크 오브 뉴욕 멜론", market: "NYSE", sp500: true},
  {ticker: "BA", name: "Boeing", kr_name: "보잉", market: "NYSE", sp500: true},
  {ticker: "BSX", name: "Boston Scientific", kr_name: "보스턴 사이언티픽", market: "NYSE", sp500: true},
  {ticker: "BMY", name: "Bristol Myers Squibb", kr_name: "브리스톨 마이어스 스큅", market: "NYSE", sp500: true},
  {ticker: "BR", name: "Broadridge Financial Solutions", kr_name: "브로드리지 파이낸셜 솔루션", market: "NYSE", sp500: true},
  {ticker: "BRO", name: "Brown & Brown", kr_name: "브라운 앤드 브라운", market: "NYSE", sp500: true},
  {ticker: "BF.B", name: "Brown–Forman", kr_name: "브라운 포맨 B", market: "NYSE", sp500: true},
  {ticker: "BLDR", name: "Builders FirstSource", kr_name: "빌더스 퍼스트소스", market: "NYSE", sp500: true},
  {ticker: "BG", name: "Bunge Global", kr_name: "번지 글로벌", market: "NYSE", sp500: true},
  {ticker: "BXP", name: "BXP, Inc.", kr_name: "BXP", market: "NYSE", sp500: true},
  {ticker: "CHRW", name: "C.H. Robinson", kr_name: "CH 로빈슨 월드와이드", market: "NYSE", sp500: true},
  {ticker: "CPT", name: "Camden Property Trust", kr_name: "캠던 프라퍼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "COF", name: "Capital One", kr_name: "캐피털 원 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "CAH", name: "Cardinal Health", kr_name: "카디널 헬스", market: "NYSE", sp500: true},
  {ticker: "CCL", name: "Carnival Corporation", kr_name: "카니발", market: "NYSE", sp500: true},
  {ticker: "CARR", name: "Carrier Global", kr_name: "캐리어 글로벌", market: "NYSE", sp500: true},
  {ticker: "CVNA", name: "Carvana", kr_name: "카바나", market: "NYSE", sp500: true},
  {ticker: "CASY", name: "Casey's", kr_name: "케이시스 제너럴 스토어스", market: "NYSE", sp500: true},
  {ticker: "CAT", name: "Caterpillar Inc.", kr_name: "캐터필러", market: "NYSE", sp500: true},
  {ticker: "CBOE", name: "Cboe Global Markets", kr_name: "씨보 글로벌 마켓", market: "NYSE", sp500: true},
  {ticker: "CBRE", name: "CBRE Group", kr_name: "CBRE 그룹", market: "NYSE", sp500: true},
  {ticker: "CDW", name: "CDW Corporation", kr_name: "CDW", market: "NYSE", sp500: true},
  {ticker: "COR", name: "Cencora", kr_name: "센코라", market: "NYSE", sp500: true},
  {ticker: "CNC", name: "Centene Corporation", kr_name: "센틴", market: "NYSE", sp500: true},
  {ticker: "CNP", name: "CenterPoint Energy", kr_name: "센터포인트 에너지", market: "NYSE", sp500: true},
  {ticker: "CF", name: "CF Industries", kr_name: "CF 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "CRL", name: "Charles River Laboratories", kr_name: "찰스 리버 래브러토리스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "SCHW", name: "Charles Schwab Corporation", kr_name: "찰스 슈왑", market: "NYSE", sp500: true},
  {ticker: "CHTR", name: "Charter Communications", kr_name: "차터 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "CVX", name: "Chevron Corporation", kr_name: "셰브론", market: "NYSE", sp500: true},
  {ticker: "CMG", name: "Chipotle Mexican Grill", kr_name: "치폴레 멕시칸 그릴", market: "NYSE", sp500: true},
  {ticker: "CB", name: "Chubb Limited", kr_name: "처브", market: "NYSE", sp500: true},
  {ticker: "CHD", name: "Church & Dwight", kr_name: "처치 앤드 드와이트", market: "NYSE", sp500: true},
  {ticker: "CIEN", name: "Ciena", kr_name: "시에나", market: "NYSE", sp500: true},
  {ticker: "CI", name: "Cigna", kr_name: "시그나 그룹", market: "NYSE", sp500: true},
  {ticker: "CINF", name: "Cincinnati Financial", kr_name: "신시내티 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "C", name: "Citigroup", kr_name: "씨티그룹", market: "NYSE", sp500: true},
  {ticker: "CFG", name: "Citizens Financial Group", kr_name: "시티즌스 파이낸셜 그룹", market: "NYSE", sp500: true},
  {ticker: "CLX", name: "Clorox", kr_name: "크로락스", market: "NYSE", sp500: true},
  {ticker: "CME", name: "CME Group", kr_name: "CME 그룹", market: "NYSE", sp500: true},
  {ticker: "CMS", name: "CMS Energy", kr_name: "CMS 에너지", market: "NYSE", sp500: true},
  {ticker: "KO", name: "Coca-Cola Company (The)", kr_name: "코카콜라", market: "NYSE", sp500: true},
  {ticker: "CTSH", name: "Cognizant", kr_name: "코그니전트 테크놀로지 솔루션스", market: "NYSE", sp500: true},
  {ticker: "COHR", name: "Coherent Corp.", kr_name: "코히어런트", market: "NYSE", sp500: true},
  {ticker: "COIN", name: "Coinbase", kr_name: "코인베이스 글로벌", market: "NYSE", sp500: true},
  {ticker: "CL", name: "Colgate-Palmolive", kr_name: "콜게이트 팜올리브", market: "NYSE", sp500: true},
  {ticker: "FIX", name: "Comfort Systems USA", kr_name: "컴포트 시스템스 USA", market: "NYSE", sp500: true},
  {ticker: "COP", name: "ConocoPhillips", kr_name: "코노코필립스", market: "NYSE", sp500: true},
  {ticker: "ED", name: "Consolidated Edison", kr_name: "컨솔리데이티드 에디슨", market: "NYSE", sp500: true},
  {ticker: "STZ", name: "Constellation Brands", kr_name: "컨스털레이션 브랜즈", market: "NYSE", sp500: true},
  {ticker: "COO", name: "Cooper Companies (The)", kr_name: "쿠퍼", market: "NYSE", sp500: true},
  {ticker: "GLW", name: "Corning Inc.", kr_name: "코닝", market: "NYSE", sp500: true},
  {ticker: "CPAY", name: "Corpay", kr_name: "코페이", market: "NYSE", sp500: true},
  {ticker: "CTVA", name: "Corteva", kr_name: "코르테바", market: "NYSE", sp500: true},
  {ticker: "CSGP", name: "CoStar Group", kr_name: "코스타 그룹", market: "NYSE", sp500: true},
  {ticker: "CRH", name: "CRH plc", kr_name: "CRH", market: "NYSE", sp500: true},
  {ticker: "CCI", name: "Crown Castle", kr_name: "크라운 캐슬", market: "NYSE", sp500: true},
  {ticker: "CMI", name: "Cummins", kr_name: "커민스", market: "NYSE", sp500: true},
  {ticker: "CVS", name: "CVS Health", kr_name: "CVS 헬스", market: "NYSE", sp500: true},
  {ticker: "DHR", name: "Danaher Corporation", kr_name: "다나허", market: "NYSE", sp500: true},
  {ticker: "DRI", name: "Darden Restaurants", kr_name: "다든 레스토랑", market: "NYSE", sp500: true},
  {ticker: "DVA", name: "DaVita", kr_name: "다비타", market: "NYSE", sp500: true},
  {ticker: "DECK", name: "Deckers Brands", kr_name: "덱커 아웃도어", market: "NYSE", sp500: true},
  {ticker: "DE", name: "Deere & Company", kr_name: "디어", market: "NYSE", sp500: true},
  {ticker: "DELL", name: "Dell Technologies", kr_name: "델 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "DAL", name: "Delta Air Lines", kr_name: "델타 에어라인스", market: "NYSE", sp500: true},
  {ticker: "DVN", name: "Devon Energy", kr_name: "데번 에너지", market: "NYSE", sp500: true},
  {ticker: "DLR", name: "Digital Realty", kr_name: "디지털 리얼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "DG", name: "Dollar General", kr_name: "달러 제너럴", market: "NYSE", sp500: true},
  {ticker: "DLTR", name: "Dollar Tree", kr_name: "달러 트리", market: "NYSE", sp500: true},
  {ticker: "D", name: "Dominion Energy", kr_name: "도미니언 에너지", market: "NYSE", sp500: true},
  {ticker: "DPZ", name: "Domino's", kr_name: "도미노 피자", market: "NYSE", sp500: true},
  {ticker: "DOV", name: "Dover Corporation", kr_name: "도버", market: "NYSE", sp500: true},
  {ticker: "DOW", name: "Dow Inc.", kr_name: "다우", market: "NYSE", sp500: true},
  {ticker: "DHI", name: "D. R. Horton", kr_name: "닥터 호턴", market: "NYSE", sp500: true},
  {ticker: "DTE", name: "DTE Energy", kr_name: "DTE 에너지", market: "NYSE", sp500: true},
  {ticker: "DUK", name: "Duke Energy", kr_name: "듀크 에너지", market: "NYSE", sp500: true},
  {ticker: "DD", name: "DuPont", kr_name: "듀폰", market: "NYSE", sp500: true},
  {ticker: "ETN", name: "Eaton Corporation", kr_name: "이턴 코퍼레이션", market: "NYSE", sp500: true},
  {ticker: "EBAY", name: "eBay Inc.", kr_name: "이베이", market: "NYSE", sp500: true},
  {ticker: "ECHO", name: "EchoStar", kr_name: "에코스타", market: "NYSE", sp500: true},
  {ticker: "ECL", name: "Ecolab", kr_name: "에코랩", market: "NYSE", sp500: true},
  {ticker: "EIX", name: "Edison International", kr_name: "에디슨 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "EW", name: "Edwards Lifesciences", kr_name: "에드워즈 라이프사이언시스", market: "NYSE", sp500: true},
  {ticker: "ELV", name: "Elevance Health", kr_name: "엘리밴스 헬스", market: "NYSE", sp500: true},
  {ticker: "EME", name: "Emcor", kr_name: "엠코 그룹", market: "NYSE", sp500: true},
  {ticker: "EMR", name: "Emerson Electric", kr_name: "에머슨 일렉트릭", market: "NYSE", sp500: true},
  {ticker: "ETR", name: "Entergy", kr_name: "엔터지", market: "NYSE", sp500: true},
  {ticker: "EOG", name: "EOG Resources", kr_name: "EOG 리소시스", market: "NYSE", sp500: true},
  {ticker: "EQT", name: "EQT Corporation", kr_name: "EQT", market: "NYSE", sp500: true},
  {ticker: "EFX", name: "Equifax", kr_name: "에퀴팩스", market: "NYSE", sp500: true},
  {ticker: "EQIX", name: "Equinix", kr_name: "에퀴닉스", market: "NYSE", sp500: true},
  {ticker: "EQR", name: "Equity Residential", kr_name: "에퀴티 레지덴셜", market: "NYSE", sp500: true},
  {ticker: "ERIE", name: "Erie Indemnity", kr_name: "이리 인뎀너티", market: "NYSE", sp500: true},
  {ticker: "ESS", name: "Essex Property Trust", kr_name: "에섹스 프라퍼티 트러스트", market: "NYSE", sp500: true},
  {ticker: "EL", name: "Estée Lauder Companies (The)", kr_name: "에스티 로더", market: "NYSE", sp500: true},
  {ticker: "EG", name: "Everest Group", kr_name: "에베레스트 그룹", market: "NYSE", sp500: true},
  {ticker: "EVRG", name: "Evergy", kr_name: "에버지", market: "NYSE", sp500: true},
  {ticker: "ES", name: "Eversource Energy", kr_name: "에버소스 에너지", market: "NYSE", sp500: true},
  {ticker: "EXE", name: "Expand Energy", kr_name: "익스팬드 에너지", market: "NYSE", sp500: true},
  {ticker: "EXPE", name: "Expedia Group", kr_name: "익스피디아 그룹", market: "NYSE", sp500: true},
  {ticker: "EXPD", name: "Expeditors International", kr_name: "익스피다이터스 인터내셔널 오브 워싱턴", market: "NYSE", sp500: true},
  {ticker: "EXR", name: "Extra Space Storage", kr_name: "엑스트라 스페이스 스토리지", market: "NYSE", sp500: true},
  {ticker: "XOM", name: "ExxonMobil", kr_name: "엑슨 모빌", market: "NYSE", sp500: true},
  {ticker: "FFIV", name: "F5, Inc.", kr_name: "F5", market: "NYSE", sp500: true},
  {ticker: "FDS", name: "FactSet", kr_name: "팩트셋 리서치 시스템스", market: "NYSE", sp500: true},
  {ticker: "FICO", name: "Fair Isaac", kr_name: "페어 아이작", market: "NYSE", sp500: true},
  {ticker: "FRT", name: "Federal Realty Investment Trust", kr_name: "페더럴 리얼티 인베스트먼트", market: "NYSE", sp500: true},
  {ticker: "FDX", name: "FedEx", kr_name: "페덱스", market: "NYSE", sp500: true},
  {ticker: "FDXF", name: "FedEx Freight", kr_name: "FedEx Freight Holding Company Inc", market: "NYSE", sp500: true},
  {ticker: "FIS", name: "Fidelity National Information Services", kr_name: "피델리티 내셔널 인포메이션 서비시스", market: "NYSE", sp500: true},
  {ticker: "FITB", name: "Fifth Third Bancorp", kr_name: "피프스 서드 뱅코프", market: "NYSE", sp500: true},
  {ticker: "FSLR", name: "First Solar", kr_name: "퍼스트 솔라", market: "NYSE", sp500: true},
  {ticker: "FE", name: "FirstEnergy", kr_name: "퍼스트에너지", market: "NYSE", sp500: true},
  {ticker: "FISV", name: "Fiserv", kr_name: "파이서브", market: "NYSE", sp500: true},
  {ticker: "FLEX", name: "Flex Ltd.", kr_name: "플렉스", market: "NYSE", sp500: true},
  {ticker: "F", name: "Ford Motor Company", kr_name: "포드 모터", market: "NYSE", sp500: true},
  {ticker: "FTV", name: "Fortive", kr_name: "포티브", market: "NYSE", sp500: true},
  {ticker: "FOXA", name: "Fox Corporation (Class A)", kr_name: "폭스 A", market: "NYSE", sp500: true},
  {ticker: "FOX", name: "Fox Corporation (Class B)", kr_name: "폭스 B", market: "NYSE", sp500: true},
  {ticker: "BEN", name: "Franklin Resources", kr_name: "프랭클린 리소시스", market: "NYSE", sp500: true},
  {ticker: "FCX", name: "Freeport-McMoRan", kr_name: "프리포트 맥모란", market: "NYSE", sp500: true},
  {ticker: "GRMN", name: "Garmin", kr_name: "가민", market: "NYSE", sp500: true},
  {ticker: "IT", name: "Gartner", kr_name: "가트너", market: "NYSE", sp500: true},
  {ticker: "GE", name: "GE Aerospace", kr_name: "GE에어로스페이스", market: "NYSE", sp500: true},
  {ticker: "GEV", name: "GE Vernova", kr_name: "GE베르노바", market: "NYSE", sp500: true},
  {ticker: "GEN", name: "Gen Digital", kr_name: "젠 디지털", market: "NYSE", sp500: true},
  {ticker: "GNRC", name: "Generac", kr_name: "제네락", market: "NYSE", sp500: true},
  {ticker: "GD", name: "General Dynamics", kr_name: "제너럴 다이내믹스", market: "NYSE", sp500: true},
  {ticker: "GIS", name: "General Mills", kr_name: "제너럴 밀스", market: "NYSE", sp500: true},
  {ticker: "GM", name: "General Motors", kr_name: "제너럴 모터스", market: "NYSE", sp500: true},
  {ticker: "GPC", name: "Genuine Parts Company", kr_name: "제뉴인 파츠", market: "NYSE", sp500: true},
  {ticker: "GPN", name: "Global Payments", kr_name: "글로벌 페이먼츠", market: "NYSE", sp500: true},
  {ticker: "GL", name: "Globe Life", kr_name: "글로브 라이프", market: "NYSE", sp500: true},
  {ticker: "GDDY", name: "GoDaddy", kr_name: "고대디", market: "NYSE", sp500: true},
  {ticker: "GS", name: "Goldman Sachs", kr_name: "골드만삭스", market: "NYSE", sp500: true},
  {ticker: "HAL", name: "Halliburton", kr_name: "할리버턴", market: "NYSE", sp500: true},
  {ticker: "HIG", name: "Hartford (The)", kr_name: "하트포드 인슈어런스 그룹", market: "NYSE", sp500: true},
  {ticker: "HAS", name: "Hasbro", kr_name: "해즈브로", market: "NYSE", sp500: true},
  {ticker: "HCA", name: "HCA Healthcare", kr_name: "HCA 헬스케어", market: "NYSE", sp500: true},
  {ticker: "DOC", name: "Healthpeak Properties", kr_name: "헬스피크 프라퍼티스", market: "NYSE", sp500: true},
  {ticker: "HSIC", name: "Henry Schein", kr_name: "헨리 셰인", market: "NYSE", sp500: true},
  {ticker: "HSY", name: "Hershey Company (The)", kr_name: "허쉬", market: "NYSE", sp500: true},
  {ticker: "HPE", name: "Hewlett Packard Enterprise", kr_name: "휴렛 팩커드 엔터프라이즈", market: "NYSE", sp500: true},
  {ticker: "HLT", name: "Hilton Worldwide", kr_name: "힐튼 월드와이드", market: "NYSE", sp500: true},
  {ticker: "HD", name: "Home Depot (The)", kr_name: "홈 디포", market: "NYSE", sp500: true},
  {ticker: "HRL", name: "Hormel Foods", kr_name: "호멜 푸즈", market: "NYSE", sp500: true},
  {ticker: "HST", name: "Host Hotels & Resorts", kr_name: "호스트 호텔스 앤드 리조츠", market: "NYSE", sp500: true},
  {ticker: "HWM", name: "Howmet Aerospace", kr_name: "하우멧 에어로스페이스", market: "NYSE", sp500: true},
  {ticker: "HPQ", name: "HP Inc.", kr_name: "HP", market: "NYSE", sp500: true},
  {ticker: "HUBB", name: "Hubbell Incorporated", kr_name: "허벨", market: "NYSE", sp500: true},
  {ticker: "HUM", name: "Humana", kr_name: "휴마나", market: "NYSE", sp500: true},
  {ticker: "HBAN", name: "Huntington Bancshares", kr_name: "헌팅턴 뱅크셰어스", market: "NYSE", sp500: true},
  {ticker: "HII", name: "Huntington Ingalls Industries", kr_name: "헌팅턴 잉걸스 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "IBM", name: "IBM", kr_name: "IBM", market: "NYSE", sp500: true},
  {ticker: "IEX", name: "IDEX Corporation", kr_name: "아이덱스", market: "NYSE", sp500: true},
  {ticker: "ITW", name: "Illinois Tool Works", kr_name: "일리노이 툴 웍스", market: "NYSE", sp500: true},
  {ticker: "INCY", name: "Incyte", kr_name: "인사이트", market: "NYSE", sp500: true},
  {ticker: "IR", name: "Ingersoll Rand", kr_name: "잉가솔랜드", market: "NYSE", sp500: true},
  {ticker: "PODD", name: "Insulet Corporation", kr_name: "인슐릿", market: "NYSE", sp500: true},
  {ticker: "IBKR", name: "Interactive Brokers", kr_name: "인터랙티브 브로커스 그룹", market: "NYSE", sp500: true},
  {ticker: "ICE", name: "Intercontinental Exchange", kr_name: "인터컨티넨털 익스체인지", market: "NYSE", sp500: true},
  {ticker: "IFF", name: "International Flavors & Fragrances", kr_name: "인터내셔널 플레이버스 앤드 프레그런스", market: "NYSE", sp500: true},
  {ticker: "IP", name: "International Paper", kr_name: "인터내셔널 페이퍼", market: "NYSE", sp500: true},
  {ticker: "IVZ", name: "Invesco", kr_name: "인베스코", market: "NYSE", sp500: true},
  {ticker: "INVH", name: "Invitation Homes", kr_name: "인비테이션 홈스", market: "NYSE", sp500: true},
  {ticker: "IQV", name: "IQVIA", kr_name: "아이큐비아", market: "NYSE", sp500: true},
  {ticker: "IRM", name: "Iron Mountain", kr_name: "아이언 마운틴", market: "NYSE", sp500: true},
  {ticker: "JBHT", name: "J.B. Hunt", kr_name: "JB 헌트 트랜스포트 서비시스", market: "NYSE", sp500: true},
  {ticker: "JBL", name: "Jabil", kr_name: "자빌", market: "NYSE", sp500: true},
  {ticker: "JKHY", name: "Jack Henry & Associates", kr_name: "헨리 잭 앤드 어소시에이츠", market: "NYSE", sp500: true},
  {ticker: "J", name: "Jacobs Solutions", kr_name: "제이콥스 솔루션스", market: "NYSE", sp500: true},
  {ticker: "JNJ", name: "Johnson & Johnson", kr_name: "존슨 앤드 존슨", market: "NYSE", sp500: true},
  {ticker: "JCI", name: "Johnson Controls", kr_name: "존슨 콘트롤즈 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "JPM", name: "JPMorgan Chase", kr_name: "제이피모간 체이스", market: "NYSE", sp500: true},
  {ticker: "KVUE", name: "Kenvue", kr_name: "켄뷰", market: "NYSE", sp500: true},
  {ticker: "KEY", name: "KeyCorp", kr_name: "키코프", market: "NYSE", sp500: true},
  {ticker: "KEYS", name: "Keysight Technologies", kr_name: "키사이트 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "KMB", name: "Kimberly-Clark", kr_name: "킴벌리클라크", market: "NYSE", sp500: true},
  {ticker: "KIM", name: "Kimco Realty", kr_name: "킴코 리얼티", market: "NYSE", sp500: true},
  {ticker: "KMI", name: "Kinder Morgan", kr_name: "킨더 모건", market: "NYSE", sp500: true},
  {ticker: "KKR", name: "KKR & Co.", kr_name: "KKR & CO", market: "NYSE", sp500: true},
  {ticker: "KR", name: "Kroger", kr_name: "크로거", market: "NYSE", sp500: true},
  {ticker: "LHX", name: "L3Harris", kr_name: "L3 해리스 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "LH", name: "Labcorp", kr_name: "랩코프", market: "NYSE", sp500: true},
  {ticker: "LVS", name: "Las Vegas Sands", kr_name: "라스베이거스 샌즈", market: "NYSE", sp500: true},
  {ticker: "LDOS", name: "Leidos", kr_name: "레이도스", market: "NYSE", sp500: true},
  {ticker: "LEN", name: "Lennar", kr_name: "레나", market: "NYSE", sp500: true},
  {ticker: "LII", name: "Lennox International", kr_name: "레녹스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "LLY", name: "Lilly (Eli)", kr_name: "일라이 릴리", market: "NYSE", sp500: true},
  {ticker: "LYV", name: "Live Nation Entertainment", kr_name: "라이브 네이션 엔터테인먼트", market: "NYSE", sp500: true},
  {ticker: "LMT", name: "Lockheed Martin", kr_name: "록히드 마틴", market: "NYSE", sp500: true},
  {ticker: "L", name: "Loews Corporation", kr_name: "로우스", market: "NYSE", sp500: true},
  {ticker: "LOW", name: "Lowe's", kr_name: "로스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "LULU", name: "Lululemon Athletica", kr_name: "룰루레몬 애슬레티카", market: "NYSE", sp500: true},
  {ticker: "LYB", name: "LyondellBasell", kr_name: "라이온델바젤 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "MTB", name: "M&T Bank", kr_name: "M&T 뱅크", market: "NYSE", sp500: true},
  {ticker: "MPC", name: "Marathon Petroleum", kr_name: "매러선 페트롤리엄", market: "NYSE", sp500: true},
  {ticker: "MRSH", name: "Marsh McLennan", kr_name: "마시 앤드 매클래넌 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "MLM", name: "Martin Marietta Materials", kr_name: "마틴 마리에타 머티리얼스", market: "NYSE", sp500: true},
  {ticker: "MAS", name: "Masco", kr_name: "매스코", market: "NYSE", sp500: true},
  {ticker: "MA", name: "Mastercard", kr_name: "마스타카드", market: "NYSE", sp500: true},
  {ticker: "MKC", name: "McCormick & Company", kr_name: "매코믹 앤드 컴퍼니", market: "NYSE", sp500: true},
  {ticker: "MCD", name: "McDonald's", kr_name: "맥도날드", market: "NYSE", sp500: true},
  {ticker: "MCK", name: "McKesson Corporation", kr_name: "매케손", market: "NYSE", sp500: true},
  {ticker: "MDT", name: "Medtronic", kr_name: "메드트로닉", market: "NYSE", sp500: true},
  {ticker: "MRK", name: "Merck & Co.", kr_name: "머크", market: "NYSE", sp500: true},
  {ticker: "MET", name: "MetLife", kr_name: "메트라이프", market: "NYSE", sp500: true},
  {ticker: "MTD", name: "Mettler Toledo", kr_name: "메틀러 톨레도 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "MGM", name: "MGM Resorts", kr_name: "MGM 리조츠 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "MAA", name: "Mid-America Apartment Communities", kr_name: "미드아메리카 어파트먼트 커뮤니티스", market: "NYSE", sp500: true},
  {ticker: "MRNA", name: "Moderna", kr_name: "모더나", market: "NYSE", sp500: true},
  {ticker: "TAP", name: "Molson Coors Beverage Company", kr_name: "몰슨 쿠어스 베버리지", market: "NYSE", sp500: true},
  {ticker: "MCO", name: "Moody's Corporation", kr_name: "무디스", market: "NYSE", sp500: true},
  {ticker: "MS", name: "Morgan Stanley", kr_name: "모간스탠리", market: "NYSE", sp500: true},
  {ticker: "MOS", name: "Mosaic Company (The)", kr_name: "모자이크", market: "NYSE", sp500: true},
  {ticker: "MSI", name: "Motorola Solutions", kr_name: "모토로라 솔루션스", market: "NYSE", sp500: true},
  {ticker: "MSCI", name: "MSCI Inc.", kr_name: "MSCI", market: "NYSE", sp500: true},
  {ticker: "NDAQ", name: "Nasdaq, Inc.", kr_name: "나스닥", market: "NYSE", sp500: true},
  {ticker: "NTAP", name: "NetApp", kr_name: "넷앱", market: "NYSE", sp500: true},
  {ticker: "NEM", name: "Newmont", kr_name: "뉴몬트", market: "NYSE", sp500: true},
  {ticker: "NWSA", name: "News Corp (Class A)", kr_name: "뉴스 코퍼레이션 A", market: "NYSE", sp500: true},
  {ticker: "NWS", name: "News Corp (Class B)", kr_name: "뉴스 코퍼레이션 B", market: "NYSE", sp500: true},
  {ticker: "NEE", name: "NextEra Energy", kr_name: "넥스트에라 에너지", market: "NYSE", sp500: true},
  {ticker: "NKE", name: "Nike, Inc.", kr_name: "나이키 B", market: "NYSE", sp500: true},
  {ticker: "NI", name: "NiSource", kr_name: "나이소스", market: "NYSE", sp500: true},
  {ticker: "NDSN", name: "Nordson Corporation", kr_name: "노드슨", market: "NYSE", sp500: true},
  {ticker: "NSC", name: "Norfolk Southern", kr_name: "노퍽서던", market: "NYSE", sp500: true},
  {ticker: "NTRS", name: "Northern Trust", kr_name: "노던 트러스트", market: "NYSE", sp500: true},
  {ticker: "NOC", name: "Northrop Grumman", kr_name: "노스롭 그루만", market: "NYSE", sp500: true},
  {ticker: "NCLH", name: "Norwegian Cruise Line Holdings", kr_name: "노르웨이지언 크루즈 라인", market: "NYSE", sp500: true},
  {ticker: "NRG", name: "NRG Energy", kr_name: "NRG 에너지", market: "NYSE", sp500: true},
  {ticker: "NUE", name: "Nucor", kr_name: "뉴코", market: "NYSE", sp500: true},
  {ticker: "NVR", name: "NVR, Inc.", kr_name: "NVR", market: "NYSE", sp500: true},
  {ticker: "OXY", name: "Occidental Petroleum", kr_name: "옥시덴털 페트롤리엄", market: "NYSE", sp500: true},
  {ticker: "OMC", name: "Omnicom Group", kr_name: "옴니콤 그룹", market: "NYSE", sp500: true},
  {ticker: "ON", name: "ON Semiconductor", kr_name: "온 세미컨덕터", market: "NYSE", sp500: true},
  {ticker: "OKE", name: "Oneok", kr_name: "원오크", market: "NYSE", sp500: true},
  {ticker: "ORCL", name: "Oracle Corporation", kr_name: "오라클", market: "NYSE", sp500: true},
  {ticker: "OTIS", name: "Otis Worldwide", kr_name: "오티스 월드와이드", market: "NYSE", sp500: true},
  {ticker: "PKG", name: "Packaging Corporation of America", kr_name: "패키징 코퍼레이션 오브 아메리카", market: "NYSE", sp500: true},
  {ticker: "PSKY", name: "Paramount Skydance Corporation", kr_name: "파라마운트 스카이댄스", market: "NYSE", sp500: true},
  {ticker: "PH", name: "Parker Hannifin", kr_name: "파카 하니핀", market: "NYSE", sp500: true},
  {ticker: "PNR", name: "Pentair", kr_name: "펜테어", market: "NYSE", sp500: true},
  {ticker: "PFE", name: "Pfizer", kr_name: "화이자", market: "NYSE", sp500: true},
  {ticker: "PCG", name: "PG&E Corporation", kr_name: "퍼시픽 가스 앤드 일렉트릭", market: "NYSE", sp500: true},
  {ticker: "PM", name: "Philip Morris International", kr_name: "필립 모리스 인터내셔널", market: "NYSE", sp500: true},
  {ticker: "PSX", name: "Phillips 66", kr_name: "필립스 66", market: "NYSE", sp500: true},
  {ticker: "PNW", name: "Pinnacle West Capital", kr_name: "피너클 웨스트 캐피털", market: "NYSE", sp500: true},
  {ticker: "PNC", name: "PNC Financial Services", kr_name: "PNC 파이낸셜 서비시스", market: "NYSE", sp500: true},
  {ticker: "PPG", name: "PPG Industries", kr_name: "PPG 인더스트리스", market: "NYSE", sp500: true},
  {ticker: "PPL", name: "PPL Corporation", kr_name: "PPL", market: "NYSE", sp500: true},
  {ticker: "PFG", name: "Principal Financial Group", kr_name: "프린서플 파이낸셜 그룹", market: "NYSE", sp500: true},
  {ticker: "PG", name: "Procter & Gamble", kr_name: "프록터 앤드 갬블", market: "NYSE", sp500: true},
  {ticker: "PGR", name: "Progressive Corporation", kr_name: "프로그레시브", market: "NYSE", sp500: true},
  {ticker: "PLD", name: "Prologis", kr_name: "프로로지스", market: "NYSE", sp500: true},
  {ticker: "PRU", name: "Prudential Financial", kr_name: "푸르덴셜 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "PEG", name: "Public Service Enterprise Group", kr_name: "퍼블릭 서비스 엔터프라이즈", market: "NYSE", sp500: true},
  {ticker: "PTC", name: "PTC Inc.", kr_name: "PTC", market: "NYSE", sp500: true},
  {ticker: "PSA", name: "Public Storage", kr_name: "퍼블릭 스토리지", market: "NYSE", sp500: true},
  {ticker: "PHM", name: "PulteGroup", kr_name: "풀티 그룹", market: "NYSE", sp500: true},
  {ticker: "PWR", name: "Quanta Services", kr_name: "콴타 서비시스", market: "NYSE", sp500: true},
  {ticker: "DGX", name: "Quest Diagnostics", kr_name: "퀘스트 다이어그노스틱스", market: "NYSE", sp500: true},
  {ticker: "Q", name: "Qnity Electronics", kr_name: "QNITY ELECTRONICS INC.", market: "NYSE", sp500: true},
  {ticker: "RL", name: "Ralph Lauren Corporation", kr_name: "랄프 로렌", market: "NYSE", sp500: true},
  {ticker: "RJF", name: "Raymond James Financial", kr_name: "레이먼드 제임스 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "RTX", name: "RTX Corporation", kr_name: "RTX", market: "NYSE", sp500: true},
  {ticker: "O", name: "Realty Income", kr_name: "리얼티 인컴", market: "NYSE", sp500: true},
  {ticker: "REG", name: "Regency Centers", kr_name: "리젠시 센터스", market: "NYSE", sp500: true},
  {ticker: "RF", name: "Regions Financial Corporation", kr_name: "리전스 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "RSG", name: "Republic Services", kr_name: "리퍼블릭 서비시스", market: "NYSE", sp500: true},
  {ticker: "RMD", name: "ResMed", kr_name: "레즈메드", market: "NYSE", sp500: true},
  {ticker: "RVTY", name: "Revvity", kr_name: "레비티", market: "NYSE", sp500: true},
  {ticker: "HOOD", name: "Robinhood Markets", kr_name: "로빈훗 마케츠", market: "NYSE", sp500: true},
  {ticker: "ROK", name: "Rockwell Automation", kr_name: "로크웰 오토메이션", market: "NYSE", sp500: true},
  {ticker: "ROL", name: "Rollins, Inc.", kr_name: "롤린스", market: "NYSE", sp500: true},
  {ticker: "RCL", name: "Royal Caribbean Group", kr_name: "로열 캐리비언 크루즈", market: "NYSE", sp500: true},
  {ticker: "SPGI", name: "S&P Global", kr_name: "S&P 글로벌", market: "NYSE", sp500: true},
  {ticker: "CRM", name: "Salesforce", kr_name: "세일스포스", market: "NYSE", sp500: true},
  {ticker: "SBAC", name: "SBA Communications", kr_name: "SBA 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "SLB", name: "Schlumberger", kr_name: "슐럼버거", market: "NYSE", sp500: true},
  {ticker: "SRE", name: "Sempra", kr_name: "셈프라", market: "NYSE", sp500: true},
  {ticker: "NOW", name: "ServiceNow", kr_name: "서비스나우", market: "NYSE", sp500: true},
  {ticker: "SHW", name: "Sherwin-Williams", kr_name: "셔윈 윌리엄스", market: "NYSE", sp500: true},
  {ticker: "SPG", name: "Simon Property Group", kr_name: "사이먼 프라퍼티 그룹", market: "NYSE", sp500: true},
  {ticker: "SWKS", name: "Skyworks Solutions", kr_name: "스카이웍스 솔루션스", market: "NYSE", sp500: true},
  {ticker: "SJM", name: "J.M. Smucker Company (The)", kr_name: "스머커", market: "NYSE", sp500: true},
  {ticker: "SW", name: "Smurfit Westrock", kr_name: "스머핏 웨스트록", market: "NYSE", sp500: true},
  {ticker: "SNA", name: "Snap-on", kr_name: "스냅 온", market: "NYSE", sp500: true},
  {ticker: "SOLV", name: "Solventum", kr_name: "솔벤텀", market: "NYSE", sp500: true},
  {ticker: "SO", name: "Southern Company", kr_name: "서던", market: "NYSE", sp500: true},
  {ticker: "LUV", name: "Southwest Airlines", kr_name: "사우스웨스트 에어라인스", market: "NYSE", sp500: true},
  {ticker: "SWK", name: "Stanley Black & Decker", kr_name: "스탠리 블랙 앤 데커", market: "NYSE", sp500: true},
  {ticker: "STT", name: "State Street Corporation", kr_name: "스테이트 스트리트", market: "NYSE", sp500: true},
  {ticker: "STLD", name: "Steel Dynamics", kr_name: "스틸 다이내믹스", market: "NYSE", sp500: true},
  {ticker: "STE", name: "Steris", kr_name: "스테리스", market: "NYSE", sp500: true},
  {ticker: "SYK", name: "Stryker Corporation", kr_name: "스트라이커", market: "NYSE", sp500: true},
  {ticker: "SMCI", name: "Supermicro", kr_name: "슈퍼 마이크로 컴퓨터", market: "NYSE", sp500: true},
  {ticker: "SYF", name: "Synchrony Financial", kr_name: "싱크로니 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "SYY", name: "Sysco", kr_name: "시스코", market: "NYSE", sp500: true},
  {ticker: "TROW", name: "T. Rowe Price", kr_name: "티 로 프라이스 그룹", market: "NYSE", sp500: true},
  {ticker: "TPR", name: "Tapestry, Inc.", kr_name: "태피스트리", market: "NYSE", sp500: true},
  {ticker: "TRGP", name: "Targa Resources", kr_name: "타르가 리소시스", market: "NYSE", sp500: true},
  {ticker: "TGT", name: "Target Corporation", kr_name: "타겟", market: "NYSE", sp500: true},
  {ticker: "TEL", name: "TE Connectivity", kr_name: "TE 커넥티비티", market: "NYSE", sp500: true},
  {ticker: "TDY", name: "Teledyne Technologies", kr_name: "텔레다인 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "TPL", name: "Texas Pacific Land Corporation", kr_name: "텍사스 퍼시픽 랜드", market: "NYSE", sp500: true},
  {ticker: "TXT", name: "Textron", kr_name: "텍스트론", market: "NYSE", sp500: true},
  {ticker: "TMO", name: "Thermo Fisher Scientific", kr_name: "써모 피셔 사이언티픽", market: "NYSE", sp500: true},
  {ticker: "TJX", name: "TJX Companies", kr_name: "TJX", market: "NYSE", sp500: true},
  {ticker: "TKO", name: "TKO Group Holdings", kr_name: "TKO 그룹", market: "NYSE", sp500: true},
  {ticker: "TTD", name: "Trade Desk (The)", kr_name: "트레이드 데스크", market: "NYSE", sp500: true},
  {ticker: "TSCO", name: "Tractor Supply", kr_name: "트랙터 서플라이", market: "NYSE", sp500: true},
  {ticker: "TT", name: "Trane Technologies", kr_name: "트레인 테크놀로지", market: "NYSE", sp500: true},
  {ticker: "TDG", name: "TransDigm Group", kr_name: "트랜스다임 그룹", market: "NYSE", sp500: true},
  {ticker: "TRV", name: "Travelers Companies (The)", kr_name: "트래블러스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "TRMB", name: "Trimble Inc.", kr_name: "트림블", market: "NYSE", sp500: true},
  {ticker: "TFC", name: "Truist Financial", kr_name: "트루이스트 파이낸셜", market: "NYSE", sp500: true},
  {ticker: "TYL", name: "Tyler Technologies", kr_name: "타일러 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "TSN", name: "Tyson Foods", kr_name: "타이슨 푸드", market: "NYSE", sp500: true},
  {ticker: "USB", name: "U.S. Bancorp", kr_name: "US 뱅코프", market: "NYSE", sp500: true},
  {ticker: "UBER", name: "Uber", kr_name: "우버 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "UDR", name: "UDR, Inc.", kr_name: "UDR", market: "NYSE", sp500: true},
  {ticker: "ULTA", name: "Ulta Beauty", kr_name: "울타 뷰티", market: "NYSE", sp500: true},
  {ticker: "UNP", name: "Union Pacific Corporation", kr_name: "유니언 퍼시픽", market: "NYSE", sp500: true},
  {ticker: "UAL", name: "United Airlines Holdings", kr_name: "유나이티드 에어라인스", market: "NYSE", sp500: true},
  {ticker: "UPS", name: "United Parcel Service", kr_name: "UPS", market: "NYSE", sp500: true},
  {ticker: "URI", name: "United Rentals", kr_name: "유나이티드 렌탈스", market: "NYSE", sp500: true},
  {ticker: "UNH", name: "UnitedHealth Group", kr_name: "유나이티드헬스 그룹", market: "NYSE", sp500: true},
  {ticker: "UHS", name: "Universal Health Services", kr_name: "유니버설 헬스 서비시스", market: "NYSE", sp500: true},
  {ticker: "VLO", name: "Valero Energy", kr_name: "발레로 에너지", market: "NYSE", sp500: true},
  {ticker: "VEEV", name: "Veeva Systems", kr_name: "비바 시스템스", market: "NYSE", sp500: true},
  {ticker: "VTR", name: "Ventas", kr_name: "벤타스", market: "NYSE", sp500: true},
  {ticker: "VLTO", name: "Veralto", kr_name: "버럴토", market: "NYSE", sp500: true},
  {ticker: "VRSN", name: "Verisign", kr_name: "베리사인", market: "NYSE", sp500: true},
  {ticker: "VRSK", name: "Verisk Analytics", kr_name: "베리스크 애널리틱스", market: "NYSE", sp500: true},
  {ticker: "VZ", name: "Verizon", kr_name: "버라이존 커뮤니케이션스", market: "NYSE", sp500: true},
  {ticker: "VRT", name: "Vertiv", kr_name: "버티브", market: "NYSE", sp500: true},
  {ticker: "VTRS", name: "Viatris", kr_name: "비아트리스", market: "NYSE", sp500: true},
  {ticker: "VICI", name: "Vici Properties", kr_name: "비치 프라퍼티스", market: "NYSE", sp500: true},
  {ticker: "V", name: "Visa Inc.", kr_name: "비자", market: "NYSE", sp500: true},
  {ticker: "VST", name: "Vistra Corp.", kr_name: "비스트라 에너지", market: "NYSE", sp500: true},
  {ticker: "VMC", name: "Vulcan Materials Company", kr_name: "벌칸 머티리얼스", market: "NYSE", sp500: true},
  {ticker: "WRB", name: "W. R. Berkley Corporation", kr_name: "WR 버클리", market: "NYSE", sp500: true},
  {ticker: "GWW", name: "W. W. Grainger", kr_name: "WW 그레인저", market: "NYSE", sp500: true},
  {ticker: "WAB", name: "Wabtec", kr_name: "왑텍", market: "NYSE", sp500: true},
  {ticker: "DIS", name: "Walt Disney Company (The)", kr_name: "월트 디즈니", market: "NYSE", sp500: true},
  {ticker: "WM", name: "Waste Management", kr_name: "웨이스트 매니지먼트", market: "NYSE", sp500: true},
  {ticker: "WAT", name: "Waters Corporation", kr_name: "워터스", market: "NYSE", sp500: true},
  {ticker: "WEC", name: "WEC Energy Group", kr_name: "WEC 에너지 그룹", market: "NYSE", sp500: true},
  {ticker: "WFC", name: "Wells Fargo", kr_name: "웰스파고", market: "NYSE", sp500: true},
  {ticker: "WELL", name: "Welltower", kr_name: "웰타워", market: "NYSE", sp500: true},
  {ticker: "WST", name: "West Pharmaceutical Services", kr_name: "웨스트 파마슈티컬 서비시즈", market: "NYSE", sp500: true},
  {ticker: "WY", name: "Weyerhaeuser", kr_name: "와이어하우저", market: "NYSE", sp500: true},
  {ticker: "WSM", name: "Williams-Sonoma, Inc.", kr_name: "윌리엄스 소노마", market: "NYSE", sp500: true},
  {ticker: "WMB", name: "Williams Companies", kr_name: "윌리엄스 컴퍼니스", market: "NYSE", sp500: true},
  {ticker: "WTW", name: "Willis Towers Watson", kr_name: "윌리스 타워스 왓슨", market: "NYSE", sp500: true},
  {ticker: "WYNN", name: "Wynn Resorts", kr_name: "윈 리조츠", market: "NYSE", sp500: true},
  {ticker: "XYL", name: "Xylem Inc.", kr_name: "자일럼", market: "NYSE", sp500: true},
  {ticker: "YUM", name: "Yum! Brands", kr_name: "염 브랜즈", market: "NYSE", sp500: true},
  {ticker: "ZBRA", name: "Zebra Technologies", kr_name: "지브라 테크놀로지스", market: "NYSE", sp500: true},
  {ticker: "ZBH", name: "Zimmer Biomet", kr_name: "짐머 바이오멧", market: "NYSE", sp500: true},
  {ticker: "ZTS", name: "Zoetis", kr_name: "조에티스", market: "NYSE", sp500: true}
] AS row
MERGE (c:Company {name: row.kr_name})
SET c:NYSE,
    c.ticker = row.ticker,
    c.en_name = row.name,
    c.is_listed = true,
    c.market = row.market,
    c.sp500 = row.sp500
REMOVE c:NASDAQ, c.kr_name;
